// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:35:33.989621

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'shipping_method_quote.zorphy.dart';
part 'shipping_method_quote.g.dart';

/// ShippingMethodQuote entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ShippingMethodQuote {

  String? get code;
  Map<String, dynamic>? get customFields;
  String? get description;
  String? get id;
  Map<String, dynamic>? get metadata;
  String? get name;
  double? get price;
  double? get priceWithTax;
}

