// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:31:25.886881

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'order_state_transition_error.zorphy.dart';
part 'order_state_transition_error.g.dart';

/// OrderStateTransitionError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderStateTransitionError {

  ErrorCode? get errorCode;
  String? get fromState;
  String? get message;
  String? get toState;
  String? get transitionError;
}

