// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:44:11.561090

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../localized_string/localized_string.dart';
import '../string_field_option/string_field_option.dart';

part 'string_custom_field_config.zorphy.dart';
part 'string_custom_field_config.g.dart';

/// StringCustomFieldConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $StringCustomFieldConfig {

  List<$LocalizedString>? get description;
  bool? get internal;
  List<$LocalizedString>? get label;
  int? get length;
  bool? get list;
  String? get name;
  bool? get nullable;
  List<$StringFieldOption>? get options;
  String? get pattern;
  bool? get readonly;
  List<Permission>? get requiresPermission;
  String? get type;
  Map<String, dynamic>? get ui;
}

