// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:31:55.880825

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'password_reset_token_expired_error.zorphy.dart';
part 'password_reset_token_expired_error.g.dart';

/// PasswordResetTokenExpiredError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PasswordResetTokenExpiredError {

  ErrorCode? get errorCode;
  String? get message;
}

