// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:26:34.834636

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'facet_sort_parameter.zorphy.dart';
part 'facet_sort_parameter.g.dart';

/// FacetSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetSortParameter {

  SortOrder? get code;
  SortOrder? get createdAt;
  SortOrder? get id;
  SortOrder? get name;
  SortOrder? get updatedAt;
}

