// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:30:36.554560

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'order_address.zorphy.dart';
part 'order_address.g.dart';

/// OrderAddress entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderAddress {

  String? get city;
  String? get company;
  String? get country;
  String? get countryCode;
  Map<String, dynamic>? get customFields;
  String? get fullName;
  String? get phoneNumber;
  String? get postalCode;
  String? get province;
  String? get streetLine1;
  String? get streetLine2;
}

