// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:59:53.528681

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../facet_value/facet_value.dart';

part 'facet_value_list.zorphy.dart';
part 'facet_value_list.g.dart';

/// FacetValueList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValueList {

  List<$FacetValue>? get items;
  int? get totalItems;
}

