// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:34:04.718162

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'product_variant_sort_parameter.zorphy.dart';
part 'product_variant_sort_parameter.g.dart';

/// ProductVariantSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductVariantSortParameter {

  SortOrder? get createdAt;
  SortOrder? get id;
  SortOrder? get name;
  SortOrder? get price;
  SortOrder? get priceWithTax;
  SortOrder? get productId;
  SortOrder? get sku;
  SortOrder? get stockLevel;
  SortOrder? get updatedAt;
}

