// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:28:57.506238

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'invalid_credentials_error.zorphy.dart';
part 'invalid_credentials_error.g.dart';

/// InvalidCredentialsError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $InvalidCredentialsError {

  String? get authenticationError;
  ErrorCode? get errorCode;
  String? get message;
}

