// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:24:26.021096

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'coordinate.zorphy.dart';
part 'coordinate.g.dart';

/// Coordinate entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Coordinate {

  double? get x;
  double? get y;
}

