// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:31:45.882260

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'password_already_set_error.zorphy.dart';
part 'password_already_set_error.g.dart';

/// PasswordAlreadySetError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PasswordAlreadySetError {

  ErrorCode? get errorCode;
  String? get message;
}

