// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:01:54.828705

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../product/product.dart';

part 'product_list.zorphy.dart';
part 'product_list.g.dart';

/// ProductList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductList {

  List<$Product>? get items;
  int? get totalItems;
}

