// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:23:16.289129

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'boolean_operators.zorphy.dart';
part 'boolean_operators.g.dart';

/// BooleanOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $BooleanOperators {

  bool? get eq;
  bool? get isNull;
}

