// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:29:37.290257

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'native_auth_strategy_error.zorphy.dart';
part 'native_auth_strategy_error.g.dart';

/// NativeAuthStrategyError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NativeAuthStrategyError {

  ErrorCode? get errorCode;
  String? get message;
}

