// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:02:34.760505

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../region_translation/region_translation.dart';
import '../region/region.dart';

part 'region.zorphy.dart';
part 'region.g.dart';

/// Region entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Region {

  String? get id;
  DateTime? get createdAt;
  DateTime? get updatedAt;
  String? get languageCode;
  String? get code;
  String? get type;
  String? get name;
  bool? get enabled;
  $Region? get parent;
  String? get parentId;
  List<$RegionTranslation>? get translations;
}

