// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:41:11.142635

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../product_option_translation/product_option_translation.dart';

part 'product_option.zorphy.dart';
part 'product_option.g.dart';

/// ProductOption entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductOption {

  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get groupId;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$ProductOptionTranslation>? get translations;
  DateTime? get updatedAt;
}

