// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:01:45.010881

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../boolean_operators/boolean_operators.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../string_operators/string_operators.dart';
import '../product_filter_parameter/product_filter_parameter.dart';

part 'product_filter_parameter.zorphy.dart';
part 'product_filter_parameter.g.dart';

/// ProductFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductFilterParameter {

  @JsonKey(name: '_and')
  List<$ProductFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$ProductFilterParameter>? get or;
  $DateOperators? get createdAt;
  $StringOperators? get description;
  $BooleanOperators? get enabled;
  $IdOperators? get id;
  $StringOperators? get languageCode;
  $StringOperators? get name;
  $StringOperators? get slug;
  $DateOperators? get updatedAt;
}

