// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:34:14.681276

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'product_variant_translation.zorphy.dart';
part 'product_variant_translation.g.dart';

/// ProductVariantTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductVariantTranslation {

  DateTime? get createdAt;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

