// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:24:06.046317

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'config_arg_definition.zorphy.dart';
part 'config_arg_definition.g.dart';

/// ConfigArgDefinition entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ConfigArgDefinition {

  Map<String, dynamic>? get defaultValue;
  String? get description;
  String? get label;
  bool? get list;
  String? get name;
  @JsonKey(name: 'required')
  bool? get required_;
  String? get type;
  Map<String, dynamic>? get ui;
}

