// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:59:22.814964

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../facet/facet.dart';

part 'facet_list.zorphy.dart';
part 'facet_list.g.dart';

/// FacetList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetList {

  List<$Facet>? get items;
  int? get totalItems;
}

