// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:25:25.474593

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'current_user_channel.zorphy.dart';
part 'current_user_channel.g.dart';

/// CurrentUserChannel entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CurrentUserChannel {

  String? get code;
  String? get id;
  String? get token;
}

