targets:
  $default:
    builders:
      zorphy:zorphy:
        enabled: true
        generate_for:
          - lib/src/domain/entities/**/*.dart
      json_serializable:
        enabled: true
        generate_for:
          - lib/src/domain/entities/**/*.dart
        options:
          explicit_to_json: true
          include_if_null: false
          any_map: true
      source_gen:combining_builder:
        enabled: true
