targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          any_map: true
      # graphql_codegen:
      #   options:
      #     assetsPath: lib/graphql/**
      #     outputDirectory: __generated__
      #     clients:
      #       - graphql_flutter
