// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:31:15.913758

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'order_sort_parameter.zorphy.dart';
part 'order_sort_parameter.g.dart';

/// OrderSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderSortParameter {

  SortOrder? get code;
  SortOrder? get createdAt;
  SortOrder? get id;
  SortOrder? get orderPlacedAt;
  SortOrder? get shipping;
  SortOrder? get shippingWithTax;
  SortOrder? get state;
  SortOrder? get subTotal;
  SortOrder? get subTotalWithTax;
  SortOrder? get total;
  SortOrder? get totalQuantity;
  SortOrder? get totalWithTax;
  SortOrder? get updatedAt;
}

