// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:03:04.508866

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../tax_rate/tax_rate.dart';

part 'tax_rate_list.zorphy.dart';
part 'tax_rate_list.g.dart';

/// TaxRateList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $TaxRateList {

  List<$TaxRate>? get items;
  int? get totalItems;
}

