// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:39:51.957093

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../localized_string/localized_string.dart';

part 'int_custom_field_config.zorphy.dart';
part 'int_custom_field_config.g.dart';

/// IntCustomFieldConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IntCustomFieldConfig {

  List<$LocalizedString>? get description;
  bool? get internal;
  List<$LocalizedString>? get label;
  bool? get list;
  int? get max;
  int? get min;
  String? get name;
  bool? get nullable;
  bool? get readonly;
  List<Permission>? get requiresPermission;
  int? get step;
  String? get type;
  Map<String, dynamic>? get ui;
}

