// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:29:47.243531

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'negative_quantity_error.zorphy.dart';
part 'negative_quantity_error.g.dart';

/// NegativeQuantityError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NegativeQuantityError {

  ErrorCode? get errorCode;
  String? get message;
}

