// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:24:35.893835

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'coupon_code_expired_error.zorphy.dart';
part 'coupon_code_expired_error.g.dart';

/// CouponCodeExpiredError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CouponCodeExpiredError {

  String? get couponCode;
  ErrorCode? get errorCode;
  String? get message;
}

