// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:01:24.692455

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../order/order.dart';

part 'order_list.zorphy.dart';
part 'order_list.g.dart';

/// OrderList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderList {

  List<$Order>? get items;
  int? get totalItems;
}

