// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:28:17.867312

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'identifier_change_token_expired_error.zorphy.dart';
part 'identifier_change_token_expired_error.g.dart';

/// IdentifierChangeTokenExpiredError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IdentifierChangeTokenExpiredError {

  ErrorCode? get errorCode;
  String? get message;
}

