// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:25:05.755773

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'create_address_input.zorphy.dart';
part 'create_address_input.g.dart';

/// CreateAddressInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CreateAddressInput {

  String? get city;
  String? get company;
  String? get countryCode;
  Map<String, dynamic>? get customFields;
  bool? get defaultBillingAddress;
  bool? get defaultShippingAddress;
  String? get fullName;
  String? get phoneNumber;
  String? get postalCode;
  String? get province;
  String? get streetLine1;
  String? get streetLine2;
}

