// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:27:46.168158

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'history_entry_sort_parameter.zorphy.dart';
part 'history_entry_sort_parameter.g.dart';

/// HistoryEntrySortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $HistoryEntrySortParameter {

  SortOrder? get createdAt;
  SortOrder? get id;
  SortOrder? get updatedAt;
}

