// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:34:24.614903

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'promotion_translation.zorphy.dart';
part 'promotion_translation.g.dart';

/// PromotionTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PromotionTranslation {

  DateTime? get createdAt;
  String? get description;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

