// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:00:34.292411

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../string_operators/string_operators.dart';
import '../history_entry_filter_parameter/history_entry_filter_parameter.dart';

part 'history_entry_filter_parameter.zorphy.dart';
part 'history_entry_filter_parameter.g.dart';

/// HistoryEntryFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $HistoryEntryFilterParameter {

  @JsonKey(name: '_and')
  List<$HistoryEntryFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$HistoryEntryFilterParameter>? get or;
  $DateOperators? get createdAt;
  $IdOperators? get id;
  $StringOperators? get type;
  $DateOperators? get updatedAt;
}

