// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:27:14.680421

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'facet_value_translation.zorphy.dart';
part 'facet_value_translation.g.dart';

/// FacetValueTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValueTranslation {

  DateTime? get createdAt;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

