// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:30:56.208598

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'order_modification_error.zorphy.dart';
part 'order_modification_error.g.dart';

/// OrderModificationError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderModificationError {

  ErrorCode? get errorCode;
  String? get message;
}

