// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:22:56.261358

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'authentication_method.zorphy.dart';
part 'authentication_method.g.dart';

/// AuthenticationMethod entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $AuthenticationMethod {

  DateTime? get createdAt;
  String? get id;
  String? get strategy;
  DateTime? get updatedAt;
}

