// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:33:05.162768

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'payment_method_translation.zorphy.dart';
part 'payment_method_translation.g.dart';

/// PaymentMethodTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PaymentMethodTranslation {

  DateTime? get createdAt;
  String? get description;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

