// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:45:01.517958

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../refund/refund.dart';

part 'payment.zorphy.dart';
part 'payment.g.dart';

/// Payment entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Payment {

  double? get amount;
  DateTime? get createdAt;
  String? get errorMessage;
  String? get id;
  Map<String, dynamic>? get metadata;
  String? get method;
  List<$Refund>? get refunds;
  String? get state;
  String? get transactionId;
  DateTime? get updatedAt;
}

