// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:46:30.363577

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../customer_filter_parameter/customer_filter_parameter.dart';
import '../customer_sort_parameter/customer_sort_parameter.dart';
import '../enums/index.dart';

part 'customer_list_options.zorphy.dart';
part 'customer_list_options.g.dart';

/// CustomerListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CustomerListOptions {

  $CustomerFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $CustomerSortParameter? get sort;
  int? get take;
}

