// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:33:54.851035

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'product_translation.zorphy.dart';
part 'product_translation.g.dart';

/// ProductTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductTranslation {

  DateTime? get createdAt;
  String? get description;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  String? get slug;
  DateTime? get updatedAt;
}

