// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:33:24.956223

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'product_option_group_translation.zorphy.dart';
part 'product_option_group_translation.g.dart';

/// ProductOptionGroupTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductOptionGroupTranslation {

  DateTime? get createdAt;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

