// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:46:40.482182

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../facet_filter_parameter/facet_filter_parameter.dart';
import '../facet_sort_parameter/facet_sort_parameter.dart';

part 'facet_list_options.zorphy.dart';
part 'facet_list_options.g.dart';

/// FacetListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetListOptions {

  $FacetFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $FacetSortParameter? get sort;
  int? get take;
}

