// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:46:20.413790

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../shipping_method/shipping_method.dart';

part 'shipping_method_list.zorphy.dart';
part 'shipping_method_list.g.dart';

/// ShippingMethodList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ShippingMethodList {

  List<$ShippingMethod>? get items;
  int? get totalItems;
}

