// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:47:40.748802

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../product_variant_filter_parameter/product_variant_filter_parameter.dart';
import '../product_variant_sort_parameter/product_variant_sort_parameter.dart';

part 'product_variant_list_options.zorphy.dart';
part 'product_variant_list_options.g.dart';

/// ProductVariantListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductVariantListOptions {

  $ProductVariantFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $ProductVariantSortParameter? get sort;
  int? get take;
}

