// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:45:41.045384

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../asset/asset.dart';

part 'asset_list.zorphy.dart';
part 'asset_list.g.dart';

/// AssetList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $AssetList {

  List<$Asset>? get items;
  int? get totalItems;
}

