// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:35:53.969324

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'single_price.zorphy.dart';
part 'single_price.g.dart';

/// SinglePrice entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $SinglePrice {

  double? get value;
}

