// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:42:00.524257

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../coordinate/coordinate.dart';
import '../enums/index.dart';
import '../tag/tag.dart';

part 'asset.zorphy.dart';
part 'asset.g.dart';

/// Asset entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Asset {

  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  int? get fileSize;
  $Coordinate? get focalPoint;
  int? get height;
  String? get id;
  String? get mimeType;
  String? get name;
  String? get preview;
  String? get source;
  List<$Tag>? get tags;
  AssetType? get type;
  DateTime? get updatedAt;
  int? get width;
}

