// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:39:02.372461

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../date_range/date_range.dart';

part 'date_operators.zorphy.dart';
part 'date_operators.g.dart';

/// DateOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $DateOperators {

  DateTime? get after;
  DateTime? get before;
  $DateRange? get between;
  DateTime? get eq;
  bool? get isNull;
}

