// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:27:56.900780

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'id_list_operators.zorphy.dart';
part 'id_list_operators.g.dart';

/// IdListOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IdListOperators {

  String? get inList;
}

