// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:26:54.653525

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'facet_value_filter_input.zorphy.dart';
part 'facet_value_filter_input.g.dart';

/// FacetValueFilterInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValueFilterInput {

  String? get and;
  List<String>? get or;
}

