// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:46:50.940359

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../facet_value_filter_parameter/facet_value_filter_parameter.dart';
import '../facet_value_sort_parameter/facet_value_sort_parameter.dart';

part 'facet_value_list_options.zorphy.dart';
part 'facet_value_list_options.g.dart';

/// FacetValueListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValueListOptions {

  $FacetValueFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $FacetValueSortParameter? get sort;
  int? get take;
}

