// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:23:56.060480

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'config_arg.zorphy.dart';
part 'config_arg.g.dart';

/// ConfigArg entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ConfigArg {

  String? get name;
  String? get value;
}

