// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:35:43.983433

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'shipping_method_translation.zorphy.dart';
part 'shipping_method_translation.g.dart';

/// ShippingMethodTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ShippingMethodTranslation {

  DateTime? get createdAt;
  String? get description;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

