// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:01:35.084615

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../asset/asset.dart';
import '../enums/index.dart';
import '../facet_value/facet_value.dart';
import '../product_option_group/product_option_group.dart';
import '../product_translation/product_translation.dart';
import '../product_variant/product_variant.dart';

part 'product.zorphy.dart';
part 'product.g.dart';

/// Product entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Product {

  List<$Asset>? get assets;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get description;
  bool? get enabled;
  List<$FacetValue>? get facetValues;
  $Asset? get featuredAsset;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$ProductOptionGroup>? get optionGroups;
  String? get slug;
  List<$ProductTranslation>? get translations;
  DateTime? get updatedAt;
  List<$ProductVariant>? get variants;
}

