// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:32:05.741762

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'password_reset_token_invalid_error.zorphy.dart';
part 'password_reset_token_invalid_error.g.dart';

/// PasswordResetTokenInvalidError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PasswordResetTokenInvalidError {

  ErrorCode? get errorCode;
  String? get message;
}

