// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:38:12.854304

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../config_arg/config_arg.dart';

part 'configurable_operation.zorphy.dart';
part 'configurable_operation.g.dart';

/// ConfigurableOperation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ConfigurableOperation {

  List<$ConfigArg>? get args;
  String? get code;
}

