// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:29:27.388937

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'native_auth_input.zorphy.dart';
part 'native_auth_input.g.dart';

/// NativeAuthInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NativeAuthInput {

  String? get password;
  String? get username;
}

