// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:36:03.943947

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'string_list_operators.zorphy.dart';
part 'string_list_operators.g.dart';

/// StringListOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $StringListOperators {

  String? get inList;
}

