// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:47:21.056828

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../collection_filter_parameter/collection_filter_parameter.dart';
import '../collection_sort_parameter/collection_sort_parameter.dart';
import '../enums/index.dart';

part 'collection_list_options.zorphy.dart';
part 'collection_list_options.g.dart';

/// CollectionListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CollectionListOptions {

  $CollectionFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $CollectionSortParameter? get sort;
  int? get take;
  bool? get topLevelOnly;
}

