// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:29:07.501759

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'localized_string.zorphy.dart';
part 'localized_string.g.dart';

/// LocalizedString entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $LocalizedString {

  LanguageCode? get languageCode;
  String? get value;
}

