// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:29:57.093317

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'no_active_order_error.zorphy.dart';
part 'no_active_order_error.g.dart';

/// NoActiveOrderError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NoActiveOrderError {

  ErrorCode? get errorCode;
  String? get message;
}

