import 'package:json_annotation/json_annotation.dart';

part 'payment_input.g.dart';

@JsonSerializable(explicitToJson: true)
class PaymentInput {
  /// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
  /// as the "metadata" argument. For example, it could contain an ID for the payment and other
  /// data generated by the payment provider.
  Map<String, dynamic> metadata;
  /// This field should correspond to the `code` property of a PaymentMethod.
  String method;

  PaymentInput({
    required this.metadata,
    required this.method,
  });

  factory PaymentInput.fromJson(Map<String, dynamic> json) => _$PaymentInputFromJson(json);
  Map<String, dynamic> toJson() => _$PaymentInputToJson(this);
}
