// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:32:45.338896

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'payment_input.zorphy.dart';
part 'payment_input.g.dart';

/// PaymentInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PaymentInput {

  Map<String, dynamic>? get metadata;
  String? get method;
}

