// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:31:06.111959

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'order_payment_state_error.zorphy.dart';
part 'order_payment_state_error.g.dart';

/// OrderPaymentStateError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderPaymentStateError {

  ErrorCode? get errorCode;
  String? get message;
}

