// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:40:31.725561

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../localized_string/localized_string.dart';

part 'string_field_option.zorphy.dart';
part 'string_field_option.g.dart';

/// StringFieldOption entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $StringFieldOption {

  List<$LocalizedString>? get label;
  String? get value;
}

