// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:59:02.726285

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../facet_translation/facet_translation.dart';
import '../facet_value/facet_value.dart';
import '../facet_value_list/facet_value_list.dart';

part 'facet.zorphy.dart';
part 'facet.g.dart';

/// Facet entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Facet {

  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$FacetTranslation>? get translations;
  DateTime? get updatedAt;
  $FacetValueList? get valueList;
  List<$FacetValue>? get values;
}

