// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:02:14.897079

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../number_operators/number_operators.dart';
import '../string_operators/string_operators.dart';
import '../product_variant_filter_parameter/product_variant_filter_parameter.dart';

part 'product_variant_filter_parameter.zorphy.dart';
part 'product_variant_filter_parameter.g.dart';

/// ProductVariantFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductVariantFilterParameter {

  @JsonKey(name: '_and')
  List<$ProductVariantFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$ProductVariantFilterParameter>? get or;
  $DateOperators? get createdAt;
  $StringOperators? get currencyCode;
  $IdOperators? get id;
  $StringOperators? get languageCode;
  $StringOperators? get name;
  $NumberOperators? get price;
  $NumberOperators? get priceWithTax;
  $IdOperators? get productId;
  $StringOperators? get sku;
  $StringOperators? get stockLevel;
  $DateOperators? get updatedAt;
}

