// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:47:30.889978

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../order_filter_parameter/order_filter_parameter.dart';
import '../order_sort_parameter/order_sort_parameter.dart';

part 'order_list_options.zorphy.dart';
part 'order_list_options.g.dart';

/// OrderListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderListOptions {

  $OrderFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $OrderSortParameter? get sort;
  int? get take;
}

