// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:45:31.198917

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../region/region.dart';
import '../region_translation/region_translation.dart';

part 'province.zorphy.dart';
part 'province.g.dart';

/// Province entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Province {

  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  bool? get enabled;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  $Region? get parent;
  String? get parentId;
  List<$RegionTranslation>? get translations;
  String? get type;
  DateTime? get updatedAt;
}

