// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:39:42.027366

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../localized_string/localized_string.dart';

part 'float_custom_field_config.zorphy.dart';
part 'float_custom_field_config.g.dart';

/// FloatCustomFieldConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FloatCustomFieldConfig {

  List<$LocalizedString>? get description;
  bool? get internal;
  List<$LocalizedString>? get label;
  bool? get list;
  double? get max;
  double? get min;
  String? get name;
  bool? get nullable;
  bool? get readonly;
  List<Permission>? get requiresPermission;
  double? get step;
  String? get type;
  Map<String, dynamic>? get ui;
}

