// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:37:33.105899

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'user_custom_fields.zorphy.dart';
part 'user_custom_fields.g.dart';

/// UserCustomFields entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UserCustomFields {

  String? get city;
  String? get deviceToken;
  String? get email;
  String? get fullName;
  String? get neighborhood;
  String? get os;
  String? get osVersion;
  String? get phoneBrand;
  String? get phoneModel;
  String? get town;
}

