// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:47:10.939899

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../product_filter_parameter/product_filter_parameter.dart';
import '../product_sort_parameter/product_sort_parameter.dart';

part 'product_list_options.zorphy.dart';
part 'product_list_options.g.dart';

/// ProductListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductListOptions {

  $ProductFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $ProductSortParameter? get sort;
  int? get take;
}

