// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:42:10.252754

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../tag/tag.dart';

part 'tag_list.zorphy.dart';
part 'tag_list.g.dart';

/// TagList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $TagList {

  List<$Tag>? get items;
  int? get totalItems;
}

