// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:45:50.908452

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../channel/channel.dart';
import '../enums/index.dart';

part 'role.zorphy.dart';
part 'role.g.dart';

/// Role entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Role {

  List<$Channel>? get channels;
  String? get code;
  DateTime? get createdAt;
  String? get description;
  String? get id;
  List<Permission>? get permissions;
  DateTime? get updatedAt;
}

