// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:01:04.589074

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../boolean_operators/boolean_operators.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../number_operators/number_operators.dart';
import '../string_operators/string_operators.dart';
import '../order_filter_parameter/order_filter_parameter.dart';

part 'order_filter_parameter.zorphy.dart';
part 'order_filter_parameter.g.dart';

/// OrderFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderFilterParameter {

  @JsonKey(name: '_and')
  List<$OrderFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$OrderFilterParameter>? get or;
  $BooleanOperators? get active;
  $StringOperators? get code;
  $DateOperators? get createdAt;
  $StringOperators? get currencyCode;
  $IdOperators? get id;
  $DateOperators? get orderPlacedAt;
  $NumberOperators? get shipping;
  $NumberOperators? get shippingWithTax;
  $StringOperators? get state;
  $NumberOperators? get subTotal;
  $NumberOperators? get subTotalWithTax;
  $NumberOperators? get total;
  $NumberOperators? get totalQuantity;
  $NumberOperators? get totalWithTax;
  $StringOperators? get type;
  $DateOperators? get updatedAt;
}

