// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:30:46.331136

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'order_limit_error.zorphy.dart';
part 'order_limit_error.g.dart';

/// OrderLimitError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderLimitError {

  ErrorCode? get errorCode;
  int? get maxItems;
  String? get message;
}

