// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:26:15.008571

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'discount.zorphy.dart';
part 'discount.g.dart';

/// Discount entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Discount {

  String? get adjustmentSource;
  double? get amount;
  double? get amountWithTax;
  String? get description;
  AdjustmentType? get type;
}

