// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:33:35.030415

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'product_option_translation.zorphy.dart';
part 'product_option_translation.g.dart';

/// ProductOptionTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductOptionTranslation {

  DateTime? get createdAt;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

