// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:22:46.025199

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'already_logged_in_error.zorphy.dart';
part 'already_logged_in_error.g.dart';

/// AlreadyLoggedInError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $AlreadyLoggedInError {

  ErrorCode? get errorCode;
  String? get message;
}

