// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:37:42.910245

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'verification_token_expired_error.zorphy.dart';
part 'verification_token_expired_error.g.dart';

/// VerificationTokenExpiredError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $VerificationTokenExpiredError {

  ErrorCode? get errorCode;
  String? get message;
}

