// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'payment_input.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

PaymentInput _$PaymentInputFromJson(Map<String, dynamic> json) {
  return _PaymentInput.fromJson(json);
}

/// @nodoc
mixin _$PaymentInput {
  /// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
  /// as the "metadata" argument. For example, it could contain an ID for the payment and other
  /// data generated by the payment provider.
  Map<String, dynamic> get metadata => throw _privateConstructorUsedError;

  /// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
  /// as the "metadata" argument. For example, it could contain an ID for the payment and other
  /// data generated by the payment provider.
  set metadata(Map<String, dynamic> value) =>
      throw _privateConstructorUsedError;

  /// This field should correspond to the `code` property of a PaymentMethod.
  String get method => throw _privateConstructorUsedError;

  /// This field should correspond to the `code` property of a PaymentMethod.
  set method(String value) => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $PaymentInputCopyWith<PaymentInput> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $PaymentInputCopyWith<$Res> {
  factory $PaymentInputCopyWith(
          PaymentInput value, $Res Function(PaymentInput) then) =
      _$PaymentInputCopyWithImpl<$Res, PaymentInput>;
  @useResult
  $Res call({Map<String, dynamic> metadata, String method});
}

/// @nodoc
class _$PaymentInputCopyWithImpl<$Res, $Val extends PaymentInput>
    implements $PaymentInputCopyWith<$Res> {
  _$PaymentInputCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? metadata = null,
    Object? method = null,
  }) {
    return _then(_value.copyWith(
      metadata: null == metadata
          ? _value.metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>,
      method: null == method
          ? _value.method
          : method // ignore: cast_nullable_to_non_nullable
              as String,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$PaymentInputImplCopyWith<$Res>
    implements $PaymentInputCopyWith<$Res> {
  factory _$$PaymentInputImplCopyWith(
          _$PaymentInputImpl value, $Res Function(_$PaymentInputImpl) then) =
      __$$PaymentInputImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call({Map<String, dynamic> metadata, String method});
}

/// @nodoc
class __$$PaymentInputImplCopyWithImpl<$Res>
    extends _$PaymentInputCopyWithImpl<$Res, _$PaymentInputImpl>
    implements _$$PaymentInputImplCopyWith<$Res> {
  __$$PaymentInputImplCopyWithImpl(
      _$PaymentInputImpl _value, $Res Function(_$PaymentInputImpl) _then)
      : super(_value, _then);

  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? metadata = null,
    Object? method = null,
  }) {
    return _then(_$PaymentInputImpl(
      metadata: null == metadata
          ? _value.metadata
          : metadata // ignore: cast_nullable_to_non_nullable
              as Map<String, dynamic>,
      method: null == method
          ? _value.method
          : method // ignore: cast_nullable_to_non_nullable
              as String,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$PaymentInputImpl extends _PaymentInput with DiagnosticableTreeMixin {
  _$PaymentInputImpl({required this.metadata, required this.method})
      : super._();

  factory _$PaymentInputImpl.fromJson(Map<String, dynamic> json) =>
      _$$PaymentInputImplFromJson(json);

  /// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
  /// as the "metadata" argument. For example, it could contain an ID for the payment and other
  /// data generated by the payment provider.
  @override
  Map<String, dynamic> metadata;

  /// This field should correspond to the `code` property of a PaymentMethod.
  @override
  String method;

  @override
  String toString({DiagnosticLevel minLevel = DiagnosticLevel.info}) {
    return 'PaymentInput(metadata: $metadata, method: $method)';
  }

  @override
  void debugFillProperties(DiagnosticPropertiesBuilder properties) {
    super.debugFillProperties(properties);
    properties
      ..add(DiagnosticsProperty('type', 'PaymentInput'))
      ..add(DiagnosticsProperty('metadata', metadata))
      ..add(DiagnosticsProperty('method', method));
  }

  @JsonKey(ignore: true)
  @override
  @pragma('vm:prefer-inline')
  _$$PaymentInputImplCopyWith<_$PaymentInputImpl> get copyWith =>
      __$$PaymentInputImplCopyWithImpl<_$PaymentInputImpl>(this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$PaymentInputImplToJson(
      this,
    );
  }
}

abstract class _PaymentInput extends PaymentInput {
  factory _PaymentInput(
      {required Map<String, dynamic> metadata,
      required String method}) = _$PaymentInputImpl;
  _PaymentInput._() : super._();

  factory _PaymentInput.fromJson(Map<String, dynamic> json) =
      _$PaymentInputImpl.fromJson;

  @override

  /// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
  /// as the "metadata" argument. For example, it could contain an ID for the payment and other
  /// data generated by the payment provider.
  Map<String, dynamic> get metadata;

  /// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
  /// as the "metadata" argument. For example, it could contain an ID for the payment and other
  /// data generated by the payment provider.
  set metadata(Map<String, dynamic> value);
  @override

  /// This field should correspond to the `code` property of a PaymentMethod.
  String get method;

  /// This field should correspond to the `code` property of a PaymentMethod.
  set method(String value);
  @override
  @JsonKey(ignore: true)
  _$$PaymentInputImplCopyWith<_$PaymentInputImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
