// GENERATED CODE - DO NOT MODIFY BY HAND
// coverage:ignore-file
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'payment_input.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

// dart format off
T _$identity<T>(T value) => value;

/// @nodoc
mixin _$PaymentInput {

/// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
/// as the "metadata" argument. For example, it could contain an ID for the payment and other
/// data generated by the payment provider.
 Map<String, dynamic> get metadata;/// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
/// as the "metadata" argument. For example, it could contain an ID for the payment and other
/// data generated by the payment provider.
 set metadata(Map<String, dynamic> value);/// This field should correspond to the `code` property of a PaymentMethod.
 String get method;/// This field should correspond to the `code` property of a PaymentMethod.
 set method(String value);
/// Create a copy of PaymentInput
/// with the given fields replaced by the non-null parameter values.
@JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
$PaymentInputCopyWith<PaymentInput> get copyWith => _$PaymentInputCopyWithImpl<PaymentInput>(this as PaymentInput, _$identity);

  /// Serializes this PaymentInput to a JSON map.
  Map<String, dynamic> toJson();




@override
String toString() {
  return 'PaymentInput(metadata: $metadata, method: $method)';
}


}

/// @nodoc
abstract mixin class $PaymentInputCopyWith<$Res>  {
  factory $PaymentInputCopyWith(PaymentInput value, $Res Function(PaymentInput) _then) = _$PaymentInputCopyWithImpl;
@useResult
$Res call({
 Map<String, dynamic> metadata, String method
});




}
/// @nodoc
class _$PaymentInputCopyWithImpl<$Res>
    implements $PaymentInputCopyWith<$Res> {
  _$PaymentInputCopyWithImpl(this._self, this._then);

  final PaymentInput _self;
  final $Res Function(PaymentInput) _then;

/// Create a copy of PaymentInput
/// with the given fields replaced by the non-null parameter values.
@pragma('vm:prefer-inline') @override $Res call({Object? metadata = null,Object? method = null,}) {
  return _then(_self.copyWith(
metadata: null == metadata ? _self.metadata : metadata // ignore: cast_nullable_to_non_nullable
as Map<String, dynamic>,method: null == method ? _self.method : method // ignore: cast_nullable_to_non_nullable
as String,
  ));
}

}


/// Adds pattern-matching-related methods to [PaymentInput].
extension PaymentInputPatterns on PaymentInput {
/// A variant of `map` that fallback to returning `orElse`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeMap<TResult extends Object?>(TResult Function( _PaymentInput value)?  $default,{required TResult orElse(),}){
final _that = this;
switch (_that) {
case _PaymentInput() when $default != null:
return $default(_that);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// Callbacks receives the raw object, upcasted.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case final Subclass2 value:
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult map<TResult extends Object?>(TResult Function( _PaymentInput value)  $default,){
final _that = this;
switch (_that) {
case _PaymentInput():
return $default(_that);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `map` that fallback to returning `null`.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case final Subclass value:
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? mapOrNull<TResult extends Object?>(TResult? Function( _PaymentInput value)?  $default,){
final _that = this;
switch (_that) {
case _PaymentInput() when $default != null:
return $default(_that);case _:
  return null;

}
}
/// A variant of `when` that fallback to an `orElse` callback.
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return orElse();
/// }
/// ```

@optionalTypeArgs TResult maybeWhen<TResult extends Object?>(TResult Function( Map<String, dynamic> metadata,  String method)?  $default,{required TResult orElse(),}) {final _that = this;
switch (_that) {
case _PaymentInput() when $default != null:
return $default(_that.metadata,_that.method);case _:
  return orElse();

}
}
/// A `switch`-like method, using callbacks.
///
/// As opposed to `map`, this offers destructuring.
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case Subclass2(:final field2):
///     return ...;
/// }
/// ```

@optionalTypeArgs TResult when<TResult extends Object?>(TResult Function( Map<String, dynamic> metadata,  String method)  $default,) {final _that = this;
switch (_that) {
case _PaymentInput():
return $default(_that.metadata,_that.method);case _:
  throw StateError('Unexpected subclass');

}
}
/// A variant of `when` that fallback to returning `null`
///
/// It is equivalent to doing:
/// ```dart
/// switch (sealedClass) {
///   case Subclass(:final field):
///     return ...;
///   case _:
///     return null;
/// }
/// ```

@optionalTypeArgs TResult? whenOrNull<TResult extends Object?>(TResult? Function( Map<String, dynamic> metadata,  String method)?  $default,) {final _that = this;
switch (_that) {
case _PaymentInput() when $default != null:
return $default(_that.metadata,_that.method);case _:
  return null;

}
}

}

/// @nodoc
@JsonSerializable()

class _PaymentInput extends PaymentInput {
   _PaymentInput({required this.metadata, required this.method}): super._();
  factory _PaymentInput.fromJson(Map<String, dynamic> json) => _$PaymentInputFromJson(json);

/// This field should contain arbitrary data passed to the specified PaymentMethodHandler's `createPayment()` method
/// as the "metadata" argument. For example, it could contain an ID for the payment and other
/// data generated by the payment provider.
@override  Map<String, dynamic> metadata;
/// This field should correspond to the `code` property of a PaymentMethod.
@override  String method;

/// Create a copy of PaymentInput
/// with the given fields replaced by the non-null parameter values.
@override @JsonKey(includeFromJson: false, includeToJson: false)
@pragma('vm:prefer-inline')
_$PaymentInputCopyWith<_PaymentInput> get copyWith => __$PaymentInputCopyWithImpl<_PaymentInput>(this, _$identity);

@override
Map<String, dynamic> toJson() {
  return _$PaymentInputToJson(this, );
}



@override
String toString() {
  return 'PaymentInput(metadata: $metadata, method: $method)';
}


}

/// @nodoc
abstract mixin class _$PaymentInputCopyWith<$Res> implements $PaymentInputCopyWith<$Res> {
  factory _$PaymentInputCopyWith(_PaymentInput value, $Res Function(_PaymentInput) _then) = __$PaymentInputCopyWithImpl;
@override @useResult
$Res call({
 Map<String, dynamic> metadata, String method
});




}
/// @nodoc
class __$PaymentInputCopyWithImpl<$Res>
    implements _$PaymentInputCopyWith<$Res> {
  __$PaymentInputCopyWithImpl(this._self, this._then);

  final _PaymentInput _self;
  final $Res Function(_PaymentInput) _then;

/// Create a copy of PaymentInput
/// with the given fields replaced by the non-null parameter values.
@override @pragma('vm:prefer-inline') $Res call({Object? metadata = null,Object? method = null,}) {
  return _then(_PaymentInput(
metadata: null == metadata ? _self.metadata : metadata // ignore: cast_nullable_to_non_nullable
as Map<String, dynamic>,method: null == method ? _self.method : method // ignore: cast_nullable_to_non_nullable
as String,
  ));
}


}

// dart format on
