// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:36:43.548169

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'tax_category.zorphy.dart';
part 'tax_category.g.dart';

/// TaxCategory entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $TaxCategory {

  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get id;
  bool? get isDefault;
  String? get name;
  DateTime? get updatedAt;
}

