// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:41:01.394566

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../number_range/number_range.dart';

part 'number_operators.zorphy.dart';
part 'number_operators.g.dart';

/// NumberOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NumberOperators {

  $NumberRange? get between;
  double? get eq;
  double? get gt;
  double? get gte;
  bool? get isNull;
  double? get lt;
  double? get lte;
}

