// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:59:43.230417

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../string_operators/string_operators.dart';
import '../facet_value_filter_parameter/facet_value_filter_parameter.dart';

part 'facet_value_filter_parameter.zorphy.dart';
part 'facet_value_filter_parameter.g.dart';

/// FacetValueFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValueFilterParameter {

  @JsonKey(name: '_and')
  List<$FacetValueFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$FacetValueFilterParameter>? get or;
  $StringOperators? get code;
  $DateOperators? get createdAt;
  $IdOperators? get facetId;
  $IdOperators? get id;
  $StringOperators? get languageCode;
  $StringOperators? get name;
  $DateOperators? get updatedAt;
}

