// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:24:45.944370

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'coupon_code_invalid_error.zorphy.dart';
part 'coupon_code_invalid_error.g.dart';

/// CouponCodeInvalidError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CouponCodeInvalidError {

  String? get couponCode;
  ErrorCode? get errorCode;
  String? get message;
}

