// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:00:44.428672

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../order/order.dart';

part 'insufficient_stock_error.zorphy.dart';
part 'insufficient_stock_error.g.dart';

/// InsufficientStockError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $InsufficientStockError {

  ErrorCode? get errorCode;
  String? get message;
  $Order? get order;
  int? get quantityAvailable;
}

