// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:40:51.533679

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../native_auth_input/native_auth_input.dart';

part 'authentication_input.zorphy.dart';
part 'authentication_input.g.dart';

/// AuthenticationInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $AuthenticationInput {

  $NativeAuthInput? get native;
}

