// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:57:52.692247

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../number_operators/number_operators.dart';
import '../string_operators/string_operators.dart';
import '../collection_filter_parameter/collection_filter_parameter.dart';

part 'collection_filter_parameter.zorphy.dart';
part 'collection_filter_parameter.g.dart';

/// CollectionFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CollectionFilterParameter {

  @JsonKey(name: '_and')
  List<$CollectionFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$CollectionFilterParameter>? get or;
  $DateOperators? get createdAt;
  $StringOperators? get description;
  $IdOperators? get id;
  $StringOperators? get languageCode;
  $StringOperators? get name;
  $IdOperators? get parentId;
  $NumberOperators? get position;
  $StringOperators? get slug;
  $DateOperators? get updatedAt;
}

