// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:46:00.825452

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../promotion/promotion.dart';

part 'promotion_list.zorphy.dart';
part 'promotion_list.g.dart';

/// PromotionList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PromotionList {

  List<$Promotion>? get items;
  int? get totalItems;
}

