// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:32:35.413181

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'payment_failed_error.zorphy.dart';
part 'payment_failed_error.g.dart';

/// PaymentFailedError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PaymentFailedError {

  ErrorCode? get errorCode;
  String? get message;
  String? get paymentErrorMessage;
}

