// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:48:10.620366

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../authentication_method/authentication_method.dart';
import '../role/role.dart';
import '../user_custom_fields/user_custom_fields.dart';

part 'user.zorphy.dart';
part 'user.g.dart';

/// User entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $User {

  List<$AuthenticationMethod>? get authenticationMethods;
  DateTime? get createdAt;
  $UserCustomFields? get customFields;
  String? get id;
  String? get identifier;
  DateTime? get lastLogin;
  List<$Role>? get roles;
  DateTime? get updatedAt;
  bool? get verified;
}

