// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:43:00.919416

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../configurable_operation/configurable_operation.dart';
import '../enums/index.dart';
import '../shipping_method_translation/shipping_method_translation.dart';

part 'shipping_method.zorphy.dart';
part 'shipping_method.g.dart';

/// ShippingMethod entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ShippingMethod {

  $ConfigurableOperation? get calculator;
  $ConfigurableOperation? get checker;
  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get description;
  String? get fulfillmentHandlerCode;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$ShippingMethodTranslation>? get translations;
  DateTime? get updatedAt;
}

