// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:35:24.103813

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'seller.zorphy.dart';
part 'seller.g.dart';

/// Seller entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Seller {

  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get id;
  String? get name;
  DateTime? get updatedAt;
}

