// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:48:00.756753

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../role/role.dart';

part 'role_list.zorphy.dart';
part 'role_list.g.dart';

/// RoleList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $RoleList {

  List<$Role>? get items;
  int? get totalItems;
}

