// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:28:37.733046

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'ineligible_payment_method_error.zorphy.dart';
part 'ineligible_payment_method_error.g.dart';

/// IneligiblePaymentMethodError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IneligiblePaymentMethodError {

  String? get eligibilityCheckerMessage;
  ErrorCode? get errorCode;
  String? get message;
}

