// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:37:23.151536

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'update_order_input.zorphy.dart';
part 'update_order_input.g.dart';

/// UpdateOrderInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UpdateOrderInput {

  Map<String, dynamic>? get customFields;
}

