// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:23:06.273592

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'boolean_list_operators.zorphy.dart';
part 'boolean_list_operators.g.dart';

/// BooleanListOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $BooleanListOperators {

  bool? get inList;
}

