// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:27:35.956343

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'history_entry.zorphy.dart';
part 'history_entry.g.dart';

/// HistoryEntry entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $HistoryEntry {

  DateTime? get createdAt;
  Map<String, dynamic>? get data;
  String? get id;
  HistoryEntryType? get type;
  DateTime? get updatedAt;
}

