// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:31:35.955915

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'order_tax_summary.zorphy.dart';
part 'order_tax_summary.g.dart';

/// OrderTaxSummary entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $OrderTaxSummary {

  String? get description;
  double? get taxBase;
  double? get taxRate;
  double? get taxTotal;
}

