// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:40:21.826325

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../localized_string/localized_string.dart';

part 'relation_custom_field_config.zorphy.dart';
part 'relation_custom_field_config.g.dart';

/// RelationCustomFieldConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $RelationCustomFieldConfig {

  List<$LocalizedString>? get description;
  String? get entity;
  bool? get internal;
  List<$LocalizedString>? get label;
  bool? get list;
  String? get name;
  bool? get nullable;
  bool? get readonly;
  List<Permission>? get requiresPermission;
  List<String>? get scalarFields;
  String? get type;
  Map<String, dynamic>? get ui;
}

