// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:33:15.009670

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'price_range.zorphy.dart';
part 'price_range.g.dart';

/// PriceRange entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PriceRange {

  double? get max;
  double? get min;
}

