// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:25:35.351165

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'customer_sort_parameter.zorphy.dart';
part 'customer_sort_parameter.g.dart';

/// CustomerSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CustomerSortParameter {

  SortOrder? get createdAt;
  SortOrder? get emailAddress;
  SortOrder? get firstName;
  SortOrder? get id;
  SortOrder? get lastName;
  SortOrder? get phoneNumber;
  SortOrder? get title;
  SortOrder? get updatedAt;
}

