// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:28:07.053472

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'id_operators.zorphy.dart';
part 'id_operators.g.dart';

/// IdOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IdOperators {

  String? get eq;
  @JsonKey(name: 'in')
  List<String>? get in_;
  bool? get isNull;
  String? get notEq;
  List<String>? get notIn;
}

