// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:32:55.270525

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'payment_method_quote.zorphy.dart';
part 'payment_method_quote.g.dart';

/// PaymentMethodQuote entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PaymentMethodQuote {

  String? get code;
  Map<String, dynamic>? get customFields;
  String? get description;
  String? get eligibilityMessage;
  String? get id;
  bool? get isEligible;
  String? get name;
}

