// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:32:25.504907

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'payment_declined_error.zorphy.dart';
part 'payment_declined_error.g.dart';

/// PaymentDeclinedError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PaymentDeclinedError {

  ErrorCode? get errorCode;
  String? get message;
  String? get paymentErrorMessage;
}

