// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:25:45.264416

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'date_list_operators.zorphy.dart';
part 'date_list_operators.g.dart';

/// DateListOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $DateListOperators {

  DateTime? get inList;
}

