// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:39:32.148434

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../localized_string/localized_string.dart';

part 'date_time_custom_field_config.zorphy.dart';
part 'date_time_custom_field_config.g.dart';

/// DateTimeCustomFieldConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $DateTimeCustomFieldConfig {

  List<$LocalizedString>? get description;
  bool? get internal;
  List<$LocalizedString>? get label;
  bool? get list;
  String? get max;
  String? get min;
  String? get name;
  bool? get nullable;
  bool? get readonly;
  List<Permission>? get requiresPermission;
  int? get step;
  String? get type;
  Map<String, dynamic>? get ui;
}

