// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:34:34.758377

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'refund_line.zorphy.dart';
part 'refund_line.g.dart';

/// RefundLine entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $RefundLine {

  String? get orderLineId;
  int? get quantity;
  String? get refundId;
}

