// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:38:32.646274

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../config_arg_input/config_arg_input.dart';

part 'configurable_operation_input.zorphy.dart';
part 'configurable_operation_input.g.dart';

/// ConfigurableOperationInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ConfigurableOperationInput {

  List<$ConfigArgInput>? get arguments;
  String? get code;
}

