// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:30:07.008167

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'not_verified_error.zorphy.dart';
part 'not_verified_error.g.dart';

/// NotVerifiedError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NotVerifiedError {

  ErrorCode? get errorCode;
  String? get message;
}

