// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:37:13.228369

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'update_customer_input.zorphy.dart';
part 'update_customer_input.g.dart';

/// UpdateCustomerInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UpdateCustomerInput {

  Map<String, dynamic>? get customFields;
  String? get firstName;
  String? get lastName;
  String? get phoneNumber;
  String? get title;
}

