// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:58:22.200864

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../address/address.dart';
import '../order_list/order_list.dart';
import '../user/user.dart';

part 'customer.zorphy.dart';
part 'customer.g.dart';

/// Customer entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Customer {

  List<$Address>? get addresses;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get emailAddress;
  String? get firstName;
  String? get id;
  String? get lastName;
  $OrderList? get orders;
  String? get phoneNumber;
  String? get title;
  DateTime? get updatedAt;
  $User? get user;
}

