// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:47:01.032700

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../history_entry_filter_parameter/history_entry_filter_parameter.dart';
import '../history_entry_sort_parameter/history_entry_sort_parameter.dart';

part 'history_entry_list_options.zorphy.dart';
part 'history_entry_list_options.g.dart';

/// HistoryEntryListOptions entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $HistoryEntryListOptions {

  $HistoryEntryFilterParameter? get filter;
  LogicalOperator? get filterOperator;
  int? get skip;
  $HistoryEntrySortParameter? get sort;
  int? get take;
}

