// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:30:16.824947

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'number_list_operators.zorphy.dart';
part 'number_list_operators.g.dart';

/// NumberListOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NumberListOperators {

  double? get inList;
}

