// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:36:53.453554

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'tax_line.zorphy.dart';
part 'tax_line.g.dart';

/// TaxLine entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $TaxLine {

  String? get description;
  double? get taxRate;
}

