// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:28:47.621760

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'ineligible_shipping_method_error.zorphy.dart';
part 'ineligible_shipping_method_error.g.dart';

/// IneligibleShippingMethodError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IneligibleShippingMethodError {

  ErrorCode? get errorCode;
  String? get message;
}

