// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:32:15.503042

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'password_validation_error.zorphy.dart';
part 'password_validation_error.g.dart';

/// PasswordValidationError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PasswordValidationError {

  ErrorCode? get errorCode;
  String? get message;
  String? get validationErrorMessage;
}

