// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:34:44.695123

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'region_translation.zorphy.dart';
part 'region_translation.g.dart';

/// RegionTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $RegionTranslation {

  DateTime? get createdAt;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

