// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:37:53.056695

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'verification_token_invalid_error.zorphy.dart';
part 'verification_token_invalid_error.g.dart';

/// VerificationTokenInvalidError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $VerificationTokenInvalidError {

  ErrorCode? get errorCode;
  String? get message;
}

