// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:41:50.596571

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../facet_value_filter_input/facet_value_filter_input.dart';
import '../search_result_sort_parameter/search_result_sort_parameter.dart';

part 'search_input.zorphy.dart';
part 'search_input.g.dart';

/// SearchInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $SearchInput {

  String? get collectionId;
  String? get collectionSlug;
  List<$FacetValueFilterInput>? get facetValueFilters;
  bool? get groupByProduct;
  bool? get inStock;
  int? get skip;
  $SearchResultSortParameter? get sort;
  int? get take;
  String? get term;
}

