// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:47:50.577588

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../province/province.dart';

part 'province_list.zorphy.dart';
part 'province_list.g.dart';

/// ProvinceList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProvinceList {

  List<$Province>? get items;
  int? get totalItems;
}

