// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:30:26.721617

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'number_range.zorphy.dart';
part 'number_range.g.dart';

/// NumberRange entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $NumberRange {

  double? get end;
  double? get start;
}

