// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:25:55.229956

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'date_range.zorphy.dart';
part 'date_range.g.dart';

/// DateRange entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $DateRange {

  DateTime? get end;
  DateTime? get start;
}

