// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:00:24.018858

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../fulfillment/fulfillment.dart';
import '../order_line/order_line.dart';

part 'fulfillment_line.zorphy.dart';
part 'fulfillment_line.g.dart';

/// FulfillmentLine entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FulfillmentLine {

  $Fulfillment? get fulfillment;
  String? get fulfillmentId;
  $OrderLine? get orderLine;
  String? get orderLineId;
  int? get quantity;
}

