// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:38:52.482501

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../current_user_channel/current_user_channel.dart';

part 'current_user.zorphy.dart';
part 'current_user.g.dart';

/// CurrentUser entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CurrentUser {

  List<$CurrentUserChannel>? get channels;
  String? get id;
  String? get identifier;
}

