// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:44:51.600218

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../product_option/product_option.dart';
import '../product_option_group_translation/product_option_group_translation.dart';

part 'product_option_group.zorphy.dart';
part 'product_option_group.g.dart';

/// ProductOptionGroup entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductOptionGroup {

  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$ProductOption>? get options;
  List<$ProductOptionGroupTranslation>? get translations;
  DateTime? get updatedAt;
}

