// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:23:36.165778

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'collection_sort_parameter.zorphy.dart';
part 'collection_sort_parameter.g.dart';

/// CollectionSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CollectionSortParameter {

  SortOrder? get createdAt;
  SortOrder? get description;
  SortOrder? get id;
  SortOrder? get name;
  SortOrder? get parentId;
  SortOrder? get position;
  SortOrder? get slug;
  SortOrder? get updatedAt;
}

