// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:36:23.728935

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'success.zorphy.dart';
part 'success.g.dart';

/// Success entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Success {

  bool? get success;
}

