// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:25:15.509790

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'create_customer_input.zorphy.dart';
part 'create_customer_input.g.dart';

/// CreateCustomerInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CreateCustomerInput {

  Map<String, dynamic>? get customFields;
  String? get emailAddress;
  String? get firstName;
  String? get lastName;
  String? get phoneNumber;
  String? get title;
}

