// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:26:44.686397

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'facet_translation.zorphy.dart';
part 'facet_translation.g.dart';

/// FacetTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetTranslation {

  DateTime? get createdAt;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  DateTime? get updatedAt;
}

