// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:39:22.194960

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../localized_string/localized_string.dart';

part 'boolean_custom_field_config.zorphy.dart';
part 'boolean_custom_field_config.g.dart';

/// BooleanCustomFieldConfig entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $BooleanCustomFieldConfig {

  List<$LocalizedString>? get description;
  bool? get internal;
  List<$LocalizedString>? get label;
  bool? get list;
  String? get name;
  bool? get nullable;
  bool? get readonly;
  List<Permission>? get requiresPermission;
  String? get type;
  Map<String, dynamic>? get ui;
}

