// Merged enum — superset of types/ and input_types/ variants
import 'package:json_annotation/json_annotation.dart';

enum ErrorCode {
  @JsonValue('ALREADY_LOGGED_IN_ERROR')
  alreadyLoggedInError,
  @JsonValue('COUPON_CODE_EXPIRED_ERROR')
  couponCodeExpiredError,
  @JsonValue('COUPON_CODE_INVALID_ERROR')
  couponCodeInvalidError,
  @JsonValue('COUPON_CODE_LIMIT_ERROR')
  couponCodeLimitError,
  @JsonValue('EMAIL_ADDRESS_CONFLICT_ERROR')
  emailAddressConflictError,
  @JsonValue('GUEST_CHECKOUT_ERROR')
  guestCheckoutError,
  @JsonValue('IDENTIFIER_CHANGE_TOKEN_EXPIRED_ERROR')
  identifierChangeTokenExpiredError,
  @JsonValue('IDENTIFIER_CHANGE_TOKEN_INVALID_ERROR')
  identifierChangeTokenInvalidError,
  @JsonValue('INELIGIBLE_PAYMENT_METHOD_ERROR')
  ineligiblePaymentMethodError,
  @JsonValue('INELIGIBLE_SHIPPING_METHOD_ERROR')
  ineligibleShippingMethodError,
  @JsonValue('INSUFFICIENT_STOCK_ERROR')
  insufficientStockError,
  @JsonValue('INVALID_CREDENTIALS_ERROR')
  invalidCredentialsError,
  @JsonValue('MISSING_PASSWORD_ERROR')
  missingPasswordError,
  @JsonValue('NATIVE_AUTH_STRATEGY_ERROR')
  nativeAuthStrategyError,
  @JsonValue('NEGATIVE_QUANTITY_ERROR')
  negativeQuantityError,
  @JsonValue('NOT_VERIFIED_ERROR')
  notVerifiedError,
  @JsonValue('NO_ACTIVE_ORDER_ERROR')
  noActiveOrderError,
  @JsonValue('ORDER_LIMIT_ERROR')
  orderLimitError,
  @JsonValue('ORDER_MODIFICATION_ERROR')
  orderModificationError,
  @JsonValue('ORDER_PAYMENT_STATE_ERROR')
  orderPaymentStateError,
  @JsonValue('ORDER_STATE_TRANSITION_ERROR')
  orderStateTransitionError,
  @JsonValue('PASSWORD_ALREADY_SET_ERROR')
  passwordAlreadySetError,
  @JsonValue('PASSWORD_RESET_TOKEN_EXPIRED_ERROR')
  passwordResetTokenExpiredError,
  @JsonValue('PASSWORD_RESET_TOKEN_INVALID_ERROR')
  passwordResetTokenInvalidError,
  @JsonValue('PASSWORD_VALIDATION_ERROR')
  passwordValidationError,
  @JsonValue('PAYMENT_DECLINED_ERROR')
  paymentDeclinedError,
  @JsonValue('PAYMENT_FAILED_ERROR')
  paymentFailedError,
  @JsonValue('UNKNOWN_ERROR')
  unknownError,
  @JsonValue('VERIFICATION_TOKEN_EXPIRED_ERROR')
  verificationTokenExpiredError,
  @JsonValue('VERIFICATION_TOKEN_INVALID_ERROR')
  verificationTokenInvalidError,
}
