// Merged enum — superset of types/ and input_types/ variants
import 'package:json_annotation/json_annotation.dart';

enum Permission {
  @JsonValue('Authenticated')
  authenticated,
  @JsonValue('CreateAdministrator')
  createAdministrator,
  @JsonValue('CreateAsset')
  createAsset,
  @JsonValue('CreateCatalog')
  createCatalog,
  @JsonValue('CreateChannel')
  createChannel,
  @JsonValue('CreateCollection')
  createCollection,
  @JsonValue('CreateCountry')
  createCountry,
  @JsonValue('CreateCustomer')
  createCustomer,
  @JsonValue('CreateCustomerGroup')
  createCustomerGroup,
  @JsonValue('CreateFacet')
  createFacet,
  @JsonValue('CreateOrder')
  createOrder,
  @JsonValue('CreatePaymentMethod')
  createPaymentMethod,
  @JsonValue('CreateProduct')
  createProduct,
  @JsonValue('CreatePromotion')
  createPromotion,
  @JsonValue('CreateSeller')
  createSeller,
  @JsonValue('CreateSettings')
  createSettings,
  @JsonValue('CreateShippingMethod')
  createShippingMethod,
  @JsonValue('CreateStockLocation')
  createStockLocation,
  @JsonValue('CreateSystem')
  createSystem,
  @JsonValue('CreateTag')
  createTag,
  @JsonValue('CreateTaxCategory')
  createTaxCategory,
  @JsonValue('CreateTaxRate')
  createTaxRate,
  @JsonValue('CreateZone')
  createZone,
  @JsonValue('DeleteAdministrator')
  deleteAdministrator,
  @JsonValue('DeleteAsset')
  deleteAsset,
  @JsonValue('DeleteCatalog')
  deleteCatalog,
  @JsonValue('DeleteChannel')
  deleteChannel,
  @JsonValue('DeleteCollection')
  deleteCollection,
  @JsonValue('DeleteCountry')
  deleteCountry,
  @JsonValue('DeleteCustomer')
  deleteCustomer,
  @JsonValue('DeleteCustomerGroup')
  deleteCustomerGroup,
  @JsonValue('DeleteFacet')
  deleteFacet,
  @JsonValue('DeleteOrder')
  deleteOrder,
  @JsonValue('DeletePaymentMethod')
  deletePaymentMethod,
  @JsonValue('DeleteProduct')
  deleteProduct,
  @JsonValue('DeletePromotion')
  deletePromotion,
  @JsonValue('DeleteSeller')
  deleteSeller,
  @JsonValue('DeleteSettings')
  deleteSettings,
  @JsonValue('DeleteShippingMethod')
  deleteShippingMethod,
  @JsonValue('DeleteStockLocation')
  deleteStockLocation,
  @JsonValue('DeleteSystem')
  deleteSystem,
  @JsonValue('DeleteTag')
  deleteTag,
  @JsonValue('DeleteTaxCategory')
  deleteTaxCategory,
  @JsonValue('DeleteTaxRate')
  deleteTaxRate,
  @JsonValue('DeleteZone')
  deleteZone,
  @JsonValue('Owner')
  owner,
  @JsonValue('Public')
  public,
  @JsonValue('ReadAdministrator')
  readAdministrator,
  @JsonValue('ReadAsset')
  readAsset,
  @JsonValue('ReadCatalog')
  readCatalog,
  @JsonValue('ReadChannel')
  readChannel,
  @JsonValue('ReadCollection')
  readCollection,
  @JsonValue('ReadCountry')
  readCountry,
  @JsonValue('ReadCustomer')
  readCustomer,
  @JsonValue('ReadCustomerGroup')
  readCustomerGroup,
  @JsonValue('ReadFacet')
  readFacet,
  @JsonValue('ReadOrder')
  readOrder,
  @JsonValue('ReadPaymentMethod')
  readPaymentMethod,
  @JsonValue('ReadProduct')
  readProduct,
  @JsonValue('ReadPromotion')
  readPromotion,
  @JsonValue('ReadSeller')
  readSeller,
  @JsonValue('ReadSettings')
  readSettings,
  @JsonValue('ReadShippingMethod')
  readShippingMethod,
  @JsonValue('ReadStockLocation')
  readStockLocation,
  @JsonValue('ReadSystem')
  readSystem,
  @JsonValue('ReadTag')
  readTag,
  @JsonValue('ReadTaxCategory')
  readTaxCategory,
  @JsonValue('ReadTaxRate')
  readTaxRate,
  @JsonValue('ReadZone')
  readZone,
  @JsonValue('SuperAdmin')
  superAdmin,
  @JsonValue('UpdateAdministrator')
  updateAdministrator,
  @JsonValue('UpdateAsset')
  updateAsset,
  @JsonValue('UpdateCatalog')
  updateCatalog,
  @JsonValue('UpdateChannel')
  updateChannel,
  @JsonValue('UpdateCollection')
  updateCollection,
  @JsonValue('UpdateCountry')
  updateCountry,
  @JsonValue('UpdateCustomer')
  updateCustomer,
  @JsonValue('UpdateCustomerGroup')
  updateCustomerGroup,
  @JsonValue('UpdateFacet')
  updateFacet,
  @JsonValue('UpdateGlobalSettings')
  updateGlobalSettings,
  @JsonValue('UpdateOrder')
  updateOrder,
  @JsonValue('UpdatePaymentMethod')
  updatePaymentMethod,
  @JsonValue('UpdateProduct')
  updateProduct,
  @JsonValue('UpdatePromotion')
  updatePromotion,
  @JsonValue('UpdateSeller')
  updateSeller,
  @JsonValue('UpdateSettings')
  updateSettings,
  @JsonValue('UpdateShippingMethod')
  updateShippingMethod,
  @JsonValue('UpdateStockLocation')
  updateStockLocation,
  @JsonValue('UpdateSystem')
  updateSystem,
  @JsonValue('UpdateTag')
  updateTag,
  @JsonValue('UpdateTaxCategory')
  updateTaxCategory,
  @JsonValue('UpdateTaxRate')
  updateTaxRate,
  @JsonValue('UpdateZone')
  updateZone,
}
