// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:23:26.228990

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'collection_breadcrumb.zorphy.dart';
part 'collection_breadcrumb.g.dart';

/// CollectionBreadcrumb entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CollectionBreadcrumb {

  String? get id;
  String? get name;
  String? get slug;
}

