// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:29:17.474360

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'missing_password_error.zorphy.dart';
part 'missing_password_error.g.dart';

/// MissingPasswordError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $MissingPasswordError {

  ErrorCode? get errorCode;
  String? get message;
}

