// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:58:52.678893

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../customer/customer.dart';

part 'customer_list.zorphy.dart';
part 'customer_list.g.dart';

/// CustomerList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CustomerList {

  List<$Customer>? get items;
  int? get totalItems;
}

