// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:38:22.751976

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../config_arg_definition/config_arg_definition.dart';

part 'configurable_operation_definition.zorphy.dart';
part 'configurable_operation_definition.g.dart';

/// ConfigurableOperationDefinition entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ConfigurableOperationDefinition {

  List<$ConfigArgDefinition>? get args;
  String? get code;
  String? get description;
}

