// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:26:24.940951

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'email_address_conflict_error.zorphy.dart';
part 'email_address_conflict_error.g.dart';

/// EmailAddressConflictError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $EmailAddressConflictError {

  ErrorCode? get errorCode;
  String? get message;
}

