// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:23:46.190782

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'collection_translation.zorphy.dart';
part 'collection_translation.g.dart';

/// CollectionTranslation entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CollectionTranslation {

  DateTime? get createdAt;
  String? get description;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  String? get slug;
  DateTime? get updatedAt;
}

