// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:36:13.824269

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'string_operators.zorphy.dart';
part 'string_operators.g.dart';

/// StringOperators entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $StringOperators {

  String? get contains;
  String? get eq;
  @JsonKey(name: 'in')
  List<String>? get in_;
  bool? get isNull;
  String? get notContains;
  String? get notEq;
  List<String>? get notIn;
  String? get regex;
}

