// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:35:04.404969

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'search_reindex_response.zorphy.dart';
part 'search_reindex_response.g.dart';

/// SearchReindexResponse entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $SearchReindexResponse {

  bool? get success;
}

