// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:58:02.541156

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../collection/collection.dart';

part 'collection_list.zorphy.dart';
part 'collection_list.g.dart';

/// CollectionList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CollectionList {

  List<$Collection>? get items;
  int? get totalItems;
}

