// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:38:03.003256

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'zone.zorphy.dart';
part 'zone.g.dart';

/// Zone entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Zone {

  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get id;
  String? get name;
  DateTime? get updatedAt;
}

