// Shim: re-exports from domain/entities/

export '../domain/entities/active_order_result/active_order_result.dart' show ActiveOrderResult;
export '../domain/entities/add_payment_to_order_result/add_payment_to_order_result.dart' show AddPaymentToOrderResult;
export '../domain/entities/address/address.dart' show Address, AddressSerialization;
export '../domain/entities/adjustment/adjustment.dart' show Adjustment, AdjustmentSerialization;
export '../domain/entities/enums/adjustment_type.dart' show AdjustmentType;
export '../domain/entities/already_logged_in_error/already_logged_in_error.dart' show AlreadyLoggedInError, AlreadyLoggedInErrorSerialization;
export '../domain/entities/apply_coupon_code_result/apply_coupon_code_result.dart' show ApplyCouponCodeResult;
export '../domain/entities/asset/asset.dart' show Asset, AssetSerialization;
export '../domain/entities/asset_list/asset_list.dart' show AssetList, AssetListSerialization;
export '../domain/entities/enums/asset_type.dart' show AssetType;
export '../domain/entities/authentication_input/authentication_input.dart' show AuthenticationInput, AuthenticationInputSerialization;
export '../domain/entities/authentication_method/authentication_method.dart' show AuthenticationMethod, AuthenticationMethodSerialization;
export '../domain/entities/authentication_result/authentication_result.dart' show AuthenticationResult;
export '../domain/entities/boolean_custom_field_config/boolean_custom_field_config.dart' show BooleanCustomFieldConfig, BooleanCustomFieldConfigSerialization;
export '../domain/entities/boolean_list_operators/boolean_list_operators.dart' show BooleanListOperators, BooleanListOperatorsSerialization;
export '../domain/entities/boolean_operators/boolean_operators.dart' show BooleanOperators, BooleanOperatorsSerialization;
export '../domain/entities/channel/channel.dart' show Channel, ChannelSerialization;
export '../domain/entities/collection/collection.dart' show Collection, CollectionSerialization;
export '../domain/entities/collection_breadcrumb/collection_breadcrumb.dart' show CollectionBreadcrumb, CollectionBreadcrumbSerialization;
export '../domain/entities/collection_filter_parameter/collection_filter_parameter.dart' show CollectionFilterParameter, CollectionFilterParameterSerialization;
export '../domain/entities/collection_list/collection_list.dart' show CollectionList, CollectionListSerialization;
export '../domain/entities/collection_list_options/collection_list_options.dart' show CollectionListOptions, CollectionListOptionsSerialization;
export '../domain/entities/collection_result/collection_result.dart' show CollectionResult, CollectionResultSerialization;
export '../domain/entities/collection_sort_parameter/collection_sort_parameter.dart' show CollectionSortParameter, CollectionSortParameterSerialization;
export '../domain/entities/collection_translation/collection_translation.dart' show CollectionTranslation, CollectionTranslationSerialization;
export '../domain/entities/config_arg/config_arg.dart' show ConfigArg, ConfigArgSerialization;
export '../domain/entities/config_arg_definition/config_arg_definition.dart' show ConfigArgDefinition, ConfigArgDefinitionSerialization;
export '../domain/entities/config_arg_input/config_arg_input.dart' show ConfigArgInput, ConfigArgInputSerialization;
export '../domain/entities/configurable_operation/configurable_operation.dart' show ConfigurableOperation, ConfigurableOperationSerialization;
export '../domain/entities/configurable_operation_definition/configurable_operation_definition.dart' show ConfigurableOperationDefinition, ConfigurableOperationDefinitionSerialization;
export '../domain/entities/configurable_operation_input/configurable_operation_input.dart' show ConfigurableOperationInput, ConfigurableOperationInputSerialization;
export '../domain/entities/coordinate/coordinate.dart' show Coordinate, CoordinateSerialization;
export '../domain/entities/country/country.dart' show Country, CountrySerialization;
export '../domain/entities/country_list/country_list.dart' show CountryList, CountryListSerialization;
export '../domain/entities/coupon_code_expired_error/coupon_code_expired_error.dart' show CouponCodeExpiredError, CouponCodeExpiredErrorSerialization;
export '../domain/entities/coupon_code_invalid_error/coupon_code_invalid_error.dart' show CouponCodeInvalidError, CouponCodeInvalidErrorSerialization;
export '../domain/entities/coupon_code_limit_error/coupon_code_limit_error.dart' show CouponCodeLimitError, CouponCodeLimitErrorSerialization;
export '../domain/entities/create_address_input/create_address_input.dart' show CreateAddressInput, CreateAddressInputSerialization;
export '../domain/entities/create_customer_input/create_customer_input.dart' show CreateCustomerInput, CreateCustomerInputSerialization;
export '../domain/entities/enums/currency_code.dart' show CurrencyCode;
export '../domain/entities/current_user/current_user.dart' show CurrentUser, CurrentUserSerialization;
export '../domain/entities/current_user_channel/current_user_channel.dart' show CurrentUserChannel, CurrentUserChannelSerialization;
export '../domain/entities/custom_field_config/custom_field_config.dart' show CustomFieldConfig;
export '../domain/entities/customer/customer.dart' show Customer, CustomerSerialization;
export '../domain/entities/customer_filter_parameter/customer_filter_parameter.dart' show CustomerFilterParameter, CustomerFilterParameterSerialization;
export '../domain/entities/customer_group/customer_group.dart' show CustomerGroup, CustomerGroupSerialization;
export '../domain/entities/customer_list/customer_list.dart' show CustomerList, CustomerListSerialization;
export '../domain/entities/customer_list_options/customer_list_options.dart' show CustomerListOptions, CustomerListOptionsSerialization;
export '../domain/entities/customer_sort_parameter/customer_sort_parameter.dart' show CustomerSortParameter, CustomerSortParameterSerialization;
export '../domain/entities/date_list_operators/date_list_operators.dart' show DateListOperators, DateListOperatorsSerialization;
export '../domain/entities/date_operators/date_operators.dart' show DateOperators, DateOperatorsSerialization;
export '../domain/entities/date_range/date_range.dart' show DateRange, DateRangeSerialization;
export '../domain/entities/date_time_custom_field_config/date_time_custom_field_config.dart' show DateTimeCustomFieldConfig, DateTimeCustomFieldConfigSerialization;
export '../domain/entities/deletion_response/deletion_response.dart' show DeletionResponse, DeletionResponseSerialization;
export '../domain/entities/enums/deletion_result.dart' show DeletionResult;
export '../domain/entities/discount/discount.dart' show Discount, DiscountSerialization;
export '../domain/entities/email_address_conflict_error/email_address_conflict_error.dart' show EmailAddressConflictError, EmailAddressConflictErrorSerialization;
export '../domain/entities/enums/error_code.dart' show ErrorCode;
export '../domain/entities/facet/facet.dart' show Facet, FacetSerialization;
export '../domain/entities/facet_filter_parameter/facet_filter_parameter.dart' show FacetFilterParameter, FacetFilterParameterSerialization;
export '../domain/entities/facet_list/facet_list.dart' show FacetList, FacetListSerialization;
export '../domain/entities/facet_list_options/facet_list_options.dart' show FacetListOptions, FacetListOptionsSerialization;
export '../domain/entities/facet_sort_parameter/facet_sort_parameter.dart' show FacetSortParameter, FacetSortParameterSerialization;
export '../domain/entities/facet_translation/facet_translation.dart' show FacetTranslation, FacetTranslationSerialization;
export '../domain/entities/facet_value/facet_value.dart' show FacetValue, FacetValueSerialization;
export '../domain/entities/facet_value_filter_input/facet_value_filter_input.dart' show FacetValueFilterInput, FacetValueFilterInputSerialization;
export '../domain/entities/facet_value_filter_parameter/facet_value_filter_parameter.dart' show FacetValueFilterParameter, FacetValueFilterParameterSerialization;
export '../domain/entities/facet_value_list/facet_value_list.dart' show FacetValueList, FacetValueListSerialization;
export '../domain/entities/facet_value_list_options/facet_value_list_options.dart' show FacetValueListOptions, FacetValueListOptionsSerialization;
export '../domain/entities/facet_value_result/facet_value_result.dart' show FacetValueResult, FacetValueResultSerialization;
export '../domain/entities/facet_value_sort_parameter/facet_value_sort_parameter.dart' show FacetValueSortParameter, FacetValueSortParameterSerialization;
export '../domain/entities/facet_value_translation/facet_value_translation.dart' show FacetValueTranslation, FacetValueTranslationSerialization;
export '../domain/entities/float_custom_field_config/float_custom_field_config.dart' show FloatCustomFieldConfig, FloatCustomFieldConfigSerialization;
export '../domain/entities/fulfillment/fulfillment.dart' show Fulfillment, FulfillmentSerialization;
export '../domain/entities/fulfillment_line/fulfillment_line.dart' show FulfillmentLine, FulfillmentLineSerialization;
export '../domain/entities/enums/global_flag.dart' show GlobalFlag;
export '../domain/entities/guest_checkout_error/guest_checkout_error.dart' show GuestCheckoutError, GuestCheckoutErrorSerialization;
export '../domain/entities/history_entry/history_entry.dart' show HistoryEntry, HistoryEntrySerialization;
export '../domain/entities/history_entry_filter_parameter/history_entry_filter_parameter.dart' show HistoryEntryFilterParameter, HistoryEntryFilterParameterSerialization;
export '../domain/entities/history_entry_list/history_entry_list.dart' show HistoryEntryList, HistoryEntryListSerialization;
export '../domain/entities/history_entry_list_options/history_entry_list_options.dart' show HistoryEntryListOptions, HistoryEntryListOptionsSerialization;
export '../domain/entities/history_entry_sort_parameter/history_entry_sort_parameter.dart' show HistoryEntrySortParameter, HistoryEntrySortParameterSerialization;
export '../domain/entities/enums/history_entry_type.dart' show HistoryEntryType;
export '../domain/entities/id_list_operators/id_list_operators.dart' show IdListOperators, IdListOperatorsSerialization;
export '../domain/entities/id_operators/id_operators.dart' show IdOperators, IdOperatorsSerialization;
export '../domain/entities/identifier_change_token_expired_error/identifier_change_token_expired_error.dart' show IdentifierChangeTokenExpiredError, IdentifierChangeTokenExpiredErrorSerialization;
export '../domain/entities/identifier_change_token_invalid_error/identifier_change_token_invalid_error.dart' show IdentifierChangeTokenInvalidError, IdentifierChangeTokenInvalidErrorSerialization;
export '../domain/entities/ineligible_payment_method_error/ineligible_payment_method_error.dart' show IneligiblePaymentMethodError, IneligiblePaymentMethodErrorSerialization;
export '../domain/entities/ineligible_shipping_method_error/ineligible_shipping_method_error.dart' show IneligibleShippingMethodError, IneligibleShippingMethodErrorSerialization;
export '../domain/entities/insufficient_stock_error/insufficient_stock_error.dart' show InsufficientStockError, InsufficientStockErrorSerialization;
export '../domain/entities/int_custom_field_config/int_custom_field_config.dart' show IntCustomFieldConfig, IntCustomFieldConfigSerialization;
export '../domain/entities/invalid_credentials_error/invalid_credentials_error.dart' show InvalidCredentialsError, InvalidCredentialsErrorSerialization;
export '../domain/entities/enums/language_code.dart' show LanguageCode;
export '../domain/entities/locale_string_custom_field_config/locale_string_custom_field_config.dart' show LocaleStringCustomFieldConfig, LocaleStringCustomFieldConfigSerialization;
export '../domain/entities/locale_text_custom_field_config/locale_text_custom_field_config.dart' show LocaleTextCustomFieldConfig, LocaleTextCustomFieldConfigSerialization;
export '../domain/entities/localized_string/localized_string.dart' show LocalizedString, LocalizedStringSerialization;
export '../domain/entities/enums/logical_operator.dart' show LogicalOperator;
export '../domain/entities/missing_password_error/missing_password_error.dart' show MissingPasswordError, MissingPasswordErrorSerialization;
export '../domain/entities/native_auth_input/native_auth_input.dart' show NativeAuthInput, NativeAuthInputSerialization;
export '../domain/entities/native_auth_strategy_error/native_auth_strategy_error.dart' show NativeAuthStrategyError, NativeAuthStrategyErrorSerialization;
export '../domain/entities/native_authentication_result/native_authentication_result.dart' show NativeAuthenticationResult;
export '../domain/entities/negative_quantity_error/negative_quantity_error.dart' show NegativeQuantityError, NegativeQuantityErrorSerialization;
export '../domain/entities/no_active_order_error/no_active_order_error.dart' show NoActiveOrderError, NoActiveOrderErrorSerialization;
export '../domain/entities/not_verified_error/not_verified_error.dart' show NotVerifiedError, NotVerifiedErrorSerialization;
export '../domain/entities/number_list_operators/number_list_operators.dart' show NumberListOperators, NumberListOperatorsSerialization;
export '../domain/entities/number_operators/number_operators.dart' show NumberOperators, NumberOperatorsSerialization;
export '../domain/entities/number_range/number_range.dart' show NumberRange, NumberRangeSerialization;
export '../domain/entities/order/order.dart' show Order, OrderSerialization;
export '../domain/entities/order_address/order_address.dart' show OrderAddress, OrderAddressSerialization;
export '../domain/entities/order_filter_parameter/order_filter_parameter.dart' show OrderFilterParameter, OrderFilterParameterSerialization;
export '../domain/entities/order_limit_error/order_limit_error.dart' show OrderLimitError, OrderLimitErrorSerialization;
export '../domain/entities/order_line/order_line.dart' show OrderLine, OrderLineSerialization;
export '../domain/entities/order_list/order_list.dart' show OrderList, OrderListSerialization;
export '../domain/entities/order_list_options/order_list_options.dart' show OrderListOptions, OrderListOptionsSerialization;
export '../domain/entities/order_modification_error/order_modification_error.dart' show OrderModificationError, OrderModificationErrorSerialization;
export '../domain/entities/order_payment_state_error/order_payment_state_error.dart' show OrderPaymentStateError, OrderPaymentStateErrorSerialization;
export '../domain/entities/order_sort_parameter/order_sort_parameter.dart' show OrderSortParameter, OrderSortParameterSerialization;
export '../domain/entities/order_state_transition_error/order_state_transition_error.dart' show OrderStateTransitionError, OrderStateTransitionErrorSerialization;
export '../domain/entities/order_tax_summary/order_tax_summary.dart' show OrderTaxSummary, OrderTaxSummarySerialization;
export '../domain/entities/enums/order_type.dart' show OrderType;
export '../domain/entities/password_already_set_error/password_already_set_error.dart' show PasswordAlreadySetError, PasswordAlreadySetErrorSerialization;
export '../domain/entities/password_reset_token_expired_error/password_reset_token_expired_error.dart' show PasswordResetTokenExpiredError, PasswordResetTokenExpiredErrorSerialization;
export '../domain/entities/password_reset_token_invalid_error/password_reset_token_invalid_error.dart' show PasswordResetTokenInvalidError, PasswordResetTokenInvalidErrorSerialization;
export '../domain/entities/password_validation_error/password_validation_error.dart' show PasswordValidationError, PasswordValidationErrorSerialization;
export '../domain/entities/payment/payment.dart' show Payment, PaymentSerialization;
export '../domain/entities/payment_declined_error/payment_declined_error.dart' show PaymentDeclinedError, PaymentDeclinedErrorSerialization;
export '../domain/entities/payment_failed_error/payment_failed_error.dart' show PaymentFailedError, PaymentFailedErrorSerialization;
export '../domain/entities/payment_input/payment_input.dart' show PaymentInput, PaymentInputSerialization;
export '../domain/entities/payment_method/payment_method.dart' show PaymentMethod, PaymentMethodSerialization;
export '../domain/entities/payment_method_quote/payment_method_quote.dart' show PaymentMethodQuote, PaymentMethodQuoteSerialization;
export '../domain/entities/payment_method_translation/payment_method_translation.dart' show PaymentMethodTranslation, PaymentMethodTranslationSerialization;
export '../domain/entities/enums/permission.dart' show Permission;
export '../domain/entities/price_range/price_range.dart' show PriceRange, PriceRangeSerialization;
export '../domain/entities/product/product.dart' show Product, ProductSerialization;
export '../domain/entities/product_filter_parameter/product_filter_parameter.dart' show ProductFilterParameter, ProductFilterParameterSerialization;
export '../domain/entities/product_list/product_list.dart' show ProductList, ProductListSerialization;
export '../domain/entities/product_list_options/product_list_options.dart' show ProductListOptions, ProductListOptionsSerialization;
export '../domain/entities/product_option/product_option.dart' show ProductOption, ProductOptionSerialization;
export '../domain/entities/product_option_group/product_option_group.dart' show ProductOptionGroup, ProductOptionGroupSerialization;
export '../domain/entities/product_option_group_translation/product_option_group_translation.dart' show ProductOptionGroupTranslation, ProductOptionGroupTranslationSerialization;
export '../domain/entities/product_option_translation/product_option_translation.dart' show ProductOptionTranslation, ProductOptionTranslationSerialization;
export '../domain/entities/product_sort_parameter/product_sort_parameter.dart' show ProductSortParameter, ProductSortParameterSerialization;
export '../domain/entities/product_translation/product_translation.dart' show ProductTranslation, ProductTranslationSerialization;
export '../domain/entities/product_variant/product_variant.dart' show ProductVariant, ProductVariantSerialization;
export '../domain/entities/product_variant_filter_parameter/product_variant_filter_parameter.dart' show ProductVariantFilterParameter, ProductVariantFilterParameterSerialization;
export '../domain/entities/product_variant_list/product_variant_list.dart' show ProductVariantList, ProductVariantListSerialization;
export '../domain/entities/product_variant_list_options/product_variant_list_options.dart' show ProductVariantListOptions, ProductVariantListOptionsSerialization;
export '../domain/entities/product_variant_sort_parameter/product_variant_sort_parameter.dart' show ProductVariantSortParameter, ProductVariantSortParameterSerialization;
export '../domain/entities/product_variant_translation/product_variant_translation.dart' show ProductVariantTranslation, ProductVariantTranslationSerialization;
export '../domain/entities/promotion/promotion.dart' show Promotion, PromotionSerialization;
export '../domain/entities/promotion_list/promotion_list.dart' show PromotionList, PromotionListSerialization;
export '../domain/entities/promotion_translation/promotion_translation.dart' show PromotionTranslation, PromotionTranslationSerialization;
export '../domain/entities/province/province.dart' show Province, ProvinceSerialization;
export '../domain/entities/province_list/province_list.dart' show ProvinceList, ProvinceListSerialization;
export '../domain/entities/refresh_customer_verification_result/refresh_customer_verification_result.dart' show RefreshCustomerVerificationResult;
export '../domain/entities/refund/refund.dart' show Refund, RefundSerialization;
export '../domain/entities/refund_line/refund_line.dart' show RefundLine, RefundLineSerialization;
export '../domain/entities/region/region.dart' show Region, RegionSerialization;
export '../domain/entities/region_translation/region_translation.dart' show RegionTranslation, RegionTranslationSerialization;
export '../domain/entities/register_customer_account_result/register_customer_account_result.dart' show RegisterCustomerAccountResult;
export '../domain/entities/register_customer_input/register_customer_input.dart' show RegisterCustomerInput, RegisterCustomerInputSerialization;
export '../domain/entities/relation_custom_field_config/relation_custom_field_config.dart' show RelationCustomFieldConfig, RelationCustomFieldConfigSerialization;
export '../domain/entities/remove_order_items_result/remove_order_items_result.dart' show RemoveOrderItemsResult;
export '../domain/entities/request_password_reset_result/request_password_reset_result.dart' show RequestPasswordResetResult;
export '../domain/entities/request_update_customer_email_address_result/request_update_customer_email_address_result.dart' show RequestUpdateCustomerEmailAddressResult;
export '../domain/entities/reset_password_result/reset_password_result.dart' show ResetPasswordResult;
export '../domain/entities/role/role.dart' show Role, RoleSerialization;
export '../domain/entities/role_list/role_list.dart' show RoleList, RoleListSerialization;
export '../domain/entities/search_input/search_input.dart' show SearchInput, SearchInputSerialization;
export '../domain/entities/search_reindex_response/search_reindex_response.dart' show SearchReindexResponse, SearchReindexResponseSerialization;
export '../domain/entities/search_response/search_response.dart' show SearchResponse, SearchResponseSerialization;
export '../domain/entities/search_result/search_result.dart' show SearchResult, SearchResultSerialization;
export '../domain/entities/search_result_asset/search_result_asset.dart' show SearchResultAsset, SearchResultAssetSerialization;
export '../domain/entities/search_result_price/search_result_price.dart' show SearchResultPrice;
export '../domain/entities/search_result_sort_parameter/search_result_sort_parameter.dart' show SearchResultSortParameter, SearchResultSortParameterSerialization;
export '../domain/entities/seller/seller.dart' show Seller, SellerSerialization;
export '../domain/entities/set_customer_for_order_result/set_customer_for_order_result.dart' show SetCustomerForOrderResult;
export '../domain/entities/set_order_shipping_method_result/set_order_shipping_method_result.dart' show SetOrderShippingMethodResult;
export '../domain/entities/shipping_line/shipping_line.dart' show ShippingLine, ShippingLineSerialization;
export '../domain/entities/shipping_method/shipping_method.dart' show ShippingMethod, ShippingMethodSerialization;
export '../domain/entities/shipping_method_list/shipping_method_list.dart' show ShippingMethodList, ShippingMethodListSerialization;
export '../domain/entities/shipping_method_quote/shipping_method_quote.dart' show ShippingMethodQuote, ShippingMethodQuoteSerialization;
export '../domain/entities/shipping_method_translation/shipping_method_translation.dart' show ShippingMethodTranslation, ShippingMethodTranslationSerialization;
export '../domain/entities/single_price/single_price.dart' show SinglePrice, SinglePriceSerialization;
export '../domain/entities/enums/sort_order.dart' show SortOrder;
export '../domain/entities/string_custom_field_config/string_custom_field_config.dart' show StringCustomFieldConfig, StringCustomFieldConfigSerialization;
export '../domain/entities/string_field_option/string_field_option.dart' show StringFieldOption, StringFieldOptionSerialization;
export '../domain/entities/string_list_operators/string_list_operators.dart' show StringListOperators, StringListOperatorsSerialization;
export '../domain/entities/string_operators/string_operators.dart' show StringOperators, StringOperatorsSerialization;
export '../domain/entities/success/success.dart' show Success, SuccessSerialization;
export '../domain/entities/surcharge/surcharge.dart' show Surcharge, SurchargeSerialization;
export '../domain/entities/tag/tag.dart' show Tag, TagSerialization;
export '../domain/entities/tag_list/tag_list.dart' show TagList, TagListSerialization;
export '../domain/entities/tax_category/tax_category.dart' show TaxCategory, TaxCategorySerialization;
export '../domain/entities/tax_line/tax_line.dart' show TaxLine, TaxLineSerialization;
export '../domain/entities/tax_rate/tax_rate.dart' show TaxRate, TaxRateSerialization;
export '../domain/entities/tax_rate_list/tax_rate_list.dart' show TaxRateList, TaxRateListSerialization;
export '../domain/entities/text_custom_field_config/text_custom_field_config.dart' show TextCustomFieldConfig, TextCustomFieldConfigSerialization;
export '../domain/entities/transition_order_to_state_result/transition_order_to_state_result.dart' show TransitionOrderToStateResult;
export '../domain/entities/update_address_input/update_address_input.dart' show UpdateAddressInput, UpdateAddressInputSerialization;
export '../domain/entities/update_customer_email_address_result/update_customer_email_address_result.dart' show UpdateCustomerEmailAddressResult;
export '../domain/entities/update_customer_input/update_customer_input.dart' show UpdateCustomerInput, UpdateCustomerInputSerialization;
export '../domain/entities/update_customer_password_result/update_customer_password_result.dart' show UpdateCustomerPasswordResult;
export '../domain/entities/update_order_input/update_order_input.dart' show UpdateOrderInput, UpdateOrderInputSerialization;
export '../domain/entities/update_order_items_result/update_order_items_result.dart' show UpdateOrderItemsResult;
export '../domain/entities/user/user.dart' show User, UserSerialization;
export '../domain/entities/user_custom_fields/user_custom_fields.dart' show UserCustomFields, UserCustomFieldsSerialization;
export '../domain/entities/verification_token_expired_error/verification_token_expired_error.dart' show VerificationTokenExpiredError, VerificationTokenExpiredErrorSerialization;
export '../domain/entities/verification_token_invalid_error/verification_token_invalid_error.dart' show VerificationTokenInvalidError, VerificationTokenInvalidErrorSerialization;
export '../domain/entities/verify_customer_account_result/verify_customer_account_result.dart' show VerifyCustomerAccountResult;
export '../domain/entities/zone/zone.dart' show Zone, ZoneSerialization;
