// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:41:30.911455

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../region_translation/region_translation.dart';

part 'country.zorphy.dart';
part 'country.g.dart';

/// Country entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Country {

  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  bool? get enabled;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  String? get parentId;
  List<$RegionTranslation>? get translations;
  String? get type;
  DateTime? get updatedAt;
}

