// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:42:20.176437

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../tax_line/tax_line.dart';

part 'surcharge.zorphy.dart';
part 'surcharge.g.dart';

/// Surcharge entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Surcharge {

  DateTime? get createdAt;
  String? get description;
  String? get id;
  double? get price;
  double? get priceWithTax;
  String? get sku;
  List<$TaxLine>? get taxLines;
  double? get taxRate;
  DateTime? get updatedAt;
}

