// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:45:21.283817

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../country/country.dart';

part 'country_list.zorphy.dart';
part 'country_list.g.dart';

/// CountryList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CountryList {

  List<$Country>? get items;
  int? get totalItems;
}

