// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:59:33.003076

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../facet/facet.dart';
import '../facet_value_translation/facet_value_translation.dart';

part 'facet_value.zorphy.dart';
part 'facet_value.g.dart';

/// FacetValue entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValue {

  String? get code;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get facetId;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$FacetValueTranslation>? get translations;
  DateTime? get updatedAt;
  $Facet? get facet;
}

