// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:58:42.748629

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../customer_list/customer_list.dart';

part 'customer_group.zorphy.dart';
part 'customer_group.g.dart';

/// CustomerGroup entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CustomerGroup {

  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  $CustomerList? get customers;
  String? get id;
  String? get name;
  DateTime? get updatedAt;
}

