// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:27:25.227678

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'guest_checkout_error.zorphy.dart';
part 'guest_checkout_error.g.dart';

/// GuestCheckoutError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $GuestCheckoutError {

  ErrorCode? get errorCode;
  String? get errorDetail;
  String? get message;
}

