// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:33:44.998024

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'product_sort_parameter.zorphy.dart';
part 'product_sort_parameter.g.dart';

/// ProductSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductSortParameter {

  SortOrder? get createdAt;
  SortOrder? get description;
  SortOrder? get id;
  SortOrder? get name;
  SortOrder? get slug;
  SortOrder? get updatedAt;
}

