// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:42:30.627291

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';
import '../seller/seller.dart';
import '../zone/zone.dart';

part 'channel.zorphy.dart';
part 'channel.g.dart';

/// Channel entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Channel {

  List<CurrencyCode>? get availableCurrencyCodes;
  List<LanguageCode>? get availableLanguageCodes;
  String? get code;
  DateTime? get createdAt;
  CurrencyCode? get currencyCode;
  Map<String, dynamic>? get customFields;
  CurrencyCode? get defaultCurrencyCode;
  LanguageCode? get defaultLanguageCode;
  $Zone? get defaultShippingZone;
  $Zone? get defaultTaxZone;
  String? get id;
  int? get outOfStockThreshold;
  bool? get pricesIncludeTax;
  $Seller? get seller;
  String? get token;
  bool? get trackInventory;
  DateTime? get updatedAt;
}

