// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:34:54.531703

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'register_customer_input.zorphy.dart';
part 'register_customer_input.g.dart';

/// RegisterCustomerInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $RegisterCustomerInput {

  String? get emailAddress;
  String? get firstName;
  String? get lastName;
  String? get password;
  String? get phoneNumber;
  String? get title;
}

