// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:46:10.719160

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../discount/discount.dart';
import '../shipping_method/shipping_method.dart';

part 'shipping_line.zorphy.dart';
part 'shipping_line.g.dart';

/// ShippingLine entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ShippingLine {

  double? get discountedPrice;
  double? get discountedPriceWithTax;
  List<$Discount>? get discounts;
  String? get id;
  double? get price;
  double? get priceWithTax;
  $ShippingMethod? get shippingMethod;
}

