// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:37:03.419679

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'update_address_input.zorphy.dart';
part 'update_address_input.g.dart';

/// UpdateAddressInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $UpdateAddressInput {

  String? get city;
  String? get company;
  String? get countryCode;
  Map<String, dynamic>? get customFields;
  bool? get defaultBillingAddress;
  bool? get defaultShippingAddress;
  String? get fullName;
  String? get id;
  String? get phoneNumber;
  String? get postalCode;
  String? get province;
  String? get streetLine1;
  String? get streetLine2;
}

