// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:24:15.992693

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'config_arg_input.zorphy.dart';
part 'config_arg_input.g.dart';

/// ConfigArgInput entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ConfigArgInput {

  String? get name;
  String? get value;
}

