// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:02:24.802609

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../product_variant/product_variant.dart';

part 'product_variant_list.zorphy.dart';
part 'product_variant_list.g.dart';

/// ProductVariantList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductVariantList {

  List<$ProductVariant>? get items;
  int? get totalItems;
}

