// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:00:13.900808

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../fulfillment_line/fulfillment_line.dart';

part 'fulfillment.zorphy.dart';
part 'fulfillment.g.dart';

/// Fulfillment entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Fulfillment {

  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  String? get id;
  List<$FulfillmentLine>? get lines;
  String? get method;
  String? get state;
  List<$FulfillmentLine>? get summary;
  String? get trackingCode;
  DateTime? get updatedAt;
}

