// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:22:35.824027

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'adjustment.zorphy.dart';
part 'adjustment.g.dart';

/// Adjustment entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Adjustment {

  String? get adjustmentSource;
  double? get amount;
  Map<String, dynamic>? get data;
  String? get description;
  AdjustmentType? get type;
}

