// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:36:33.732666

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'tag.zorphy.dart';
part 'tag.g.dart';

/// Tag entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Tag {

  DateTime? get createdAt;
  String? get id;
  DateTime? get updatedAt;
  String? get value;
}

