// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:45:11.382094

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../country/country.dart';

part 'address.zorphy.dart';
part 'address.g.dart';

/// Address entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Address {

  String? get city;
  String? get company;
  $Country? get country;
  DateTime? get createdAt;
  Map<String, dynamic>? get customFields;
  bool? get defaultBillingAddress;
  bool? get defaultShippingAddress;
  String? get fullName;
  String? get id;
  String? get phoneNumber;
  String? get postalCode;
  String? get province;
  String? get streetLine1;
  String? get streetLine2;
  DateTime? get updatedAt;
}

