// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:28:27.782066

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'identifier_change_token_invalid_error.zorphy.dart';
part 'identifier_change_token_invalid_error.g.dart';

/// IdentifierChangeTokenInvalidError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $IdentifierChangeTokenInvalidError {

  ErrorCode? get errorCode;
  String? get message;
}

