// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:26:05.168383

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'deletion_response.zorphy.dart';
part 'deletion_response.g.dart';

/// DeletionResponse entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $DeletionResponse {

  String? get message;
  DeletionResult? get result;
}

