// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:27:04.527736

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'facet_value_sort_parameter.zorphy.dart';
part 'facet_value_sort_parameter.g.dart';

/// FacetValueSortParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $FacetValueSortParameter {

  SortOrder? get code;
  SortOrder? get createdAt;
  SortOrder? get facetId;
  SortOrder? get id;
  SortOrder? get name;
  SortOrder? get updatedAt;
}

