// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:24:55.846104

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'coupon_code_limit_error.zorphy.dart';
part 'coupon_code_limit_error.g.dart';

/// CouponCodeLimitError entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CouponCodeLimitError {

  String? get couponCode;
  ErrorCode? get errorCode;
  int? get limit;
  String? get message;
}

