// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:39:12.277631

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../history_entry/history_entry.dart';

part 'history_entry_list.zorphy.dart';
part 'history_entry_list.g.dart';

/// HistoryEntryList entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $HistoryEntryList {

  List<$HistoryEntry>? get items;
  int? get totalItems;
}

