// Auto-generated by Zorphy
// Generated at: 2026-08-13T23:02:04.884637

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../asset/asset.dart';
import '../enums/index.dart';
import '../facet_value/facet_value.dart';
import '../product_option/product_option.dart';
import '../product_variant_translation/product_variant_translation.dart';
import '../tax_category/tax_category.dart';

part 'product_variant.zorphy.dart';
part 'product_variant.g.dart';

/// ProductVariant entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ProductVariant {

  List<$Asset>? get assets;
  DateTime? get createdAt;
  CurrencyCode? get currencyCode;
  Map<String, dynamic>? get customFields;
  List<$FacetValue>? get facetValues;
  $Asset? get featuredAsset;
  String? get id;
  LanguageCode? get languageCode;
  String? get name;
  List<$ProductOption>? get options;
  double? get price;
  double? get priceWithTax;
  String? get productId;
  String? get sku;
  String? get stockLevel;
  $TaxCategory? get taxCategory;
  List<$ProductVariantTranslation>? get translations;
  DateTime? get updatedAt;
}

