// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_variant.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductVariant _$ProductVariantFromJson(Map json) => ProductVariant(
  assets: (json['assets'] as List<dynamic>?)
      ?.map(
        (e) => e == null
            ? null
            : Asset.fromJson(Map<String, dynamic>.from(e as Map)),
      )
      .toList(),
  createdAt: json['createdAt'] == null
      ? null
      : DateTime.parse(json['createdAt'] as String),
  currencyCode: $enumDecodeNullable(
    _$CurrencyCodeEnumMap,
    json['currencyCode'],
  ),
  customFields: (json['customFields'] as Map?)?.map(
    (k, e) => MapEntry(k as String, e),
  ),
  facetValues: (json['facetValues'] as List<dynamic>?)
      ?.map(
        (e) => e == null
            ? null
            : FacetValue.fromJson(Map<String, dynamic>.from(e as Map)),
      )
      .toList(),
  featuredAsset: json['featuredAsset'] == null
      ? null
      : Asset.fromJson(Map<String, dynamic>.from(json['featuredAsset'] as Map)),
  id: json['id'] as String?,
  languageCode: $enumDecodeNullable(
    _$LanguageCodeEnumMap,
    json['languageCode'],
  ),
  name: json['name'] as String?,
  options: (json['options'] as List<dynamic>?)
      ?.map(
        (e) => e == null
            ? null
            : ProductOption.fromJson(Map<String, dynamic>.from(e as Map)),
      )
      .toList(),
  price: (json['price'] as num?)?.toDouble(),
  priceWithTax: (json['priceWithTax'] as num?)?.toDouble(),
  product: json['product'] == null
      ? null
      : Product.fromJson(Map<String, dynamic>.from(json['product'] as Map)),
  productId: json['productId'] as String?,
  sku: json['sku'] as String?,
  stockLevel: json['stockLevel'] as String?,
  taxCategory: json['taxCategory'] == null
      ? null
      : TaxCategory.fromJson(
          Map<String, dynamic>.from(json['taxCategory'] as Map),
        ),
  taxRateApplied: json['taxRateApplied'] == null
      ? null
      : TaxRate.fromJson(
          Map<String, dynamic>.from(json['taxRateApplied'] as Map),
        ),
  translations: (json['translations'] as List<dynamic>?)
      ?.map(
        (e) => e == null
            ? null
            : ProductVariantTranslation.fromJson(
                Map<String, dynamic>.from(e as Map),
              ),
      )
      .toList(),
  updatedAt: json['updatedAt'] == null
      ? null
      : DateTime.parse(json['updatedAt'] as String),
);

Map<String, dynamic> _$ProductVariantToJson(ProductVariant instance) =>
    <String, dynamic>{
      'assets': ?instance.assets?.map((e) => e?.toJson()).toList(),
      'createdAt': ?instance.createdAt?.toIso8601String(),
      'currencyCode': ?_$CurrencyCodeEnumMap[instance.currencyCode],
      'customFields': ?instance.customFields,
      'facetValues': ?instance.facetValues?.map((e) => e?.toJson()).toList(),
      'featuredAsset': ?instance.featuredAsset?.toJson(),
      'id': ?instance.id,
      'languageCode': ?_$LanguageCodeEnumMap[instance.languageCode],
      'name': ?instance.name,
      'options': ?instance.options?.map((e) => e?.toJson()).toList(),
      'price': ?instance.price,
      'priceWithTax': ?instance.priceWithTax,
      'product': ?instance.product?.toJson(),
      'productId': ?instance.productId,
      'sku': ?instance.sku,
      'stockLevel': ?instance.stockLevel,
      'taxCategory': ?instance.taxCategory?.toJson(),
      'taxRateApplied': ?instance.taxRateApplied?.toJson(),
      'translations': ?instance.translations?.map((e) => e?.toJson()).toList(),
      'updatedAt': ?instance.updatedAt?.toIso8601String(),
    };

const _$CurrencyCodeEnumMap = {
  CurrencyCode.aed: 'AED',
  CurrencyCode.afn: 'AFN',
  CurrencyCode.all: 'ALL',
  CurrencyCode.amd: 'AMD',
  CurrencyCode.ang: 'ANG',
  CurrencyCode.aoa: 'AOA',
  CurrencyCode.ars: 'ARS',
  CurrencyCode.aud: 'AUD',
  CurrencyCode.awg: 'AWG',
  CurrencyCode.azn: 'AZN',
  CurrencyCode.bam: 'BAM',
  CurrencyCode.bbd: 'BBD',
  CurrencyCode.bdt: 'BDT',
  CurrencyCode.bgn: 'BGN',
  CurrencyCode.bhd: 'BHD',
  CurrencyCode.bif: 'BIF',
  CurrencyCode.bmd: 'BMD',
  CurrencyCode.bnd: 'BND',
  CurrencyCode.bob: 'BOB',
  CurrencyCode.brl: 'BRL',
  CurrencyCode.bsd: 'BSD',
  CurrencyCode.btn: 'BTN',
  CurrencyCode.bwp: 'BWP',
  CurrencyCode.byn: 'BYN',
  CurrencyCode.bzd: 'BZD',
  CurrencyCode.cad: 'CAD',
  CurrencyCode.cdf: 'CDF',
  CurrencyCode.chf: 'CHF',
  CurrencyCode.clp: 'CLP',
  CurrencyCode.cny: 'CNY',
  CurrencyCode.cop: 'COP',
  CurrencyCode.crc: 'CRC',
  CurrencyCode.cuc: 'CUC',
  CurrencyCode.cup: 'CUP',
  CurrencyCode.cve: 'CVE',
  CurrencyCode.czk: 'CZK',
  CurrencyCode.djf: 'DJF',
  CurrencyCode.dkk: 'DKK',
  CurrencyCode.dop: 'DOP',
  CurrencyCode.dzd: 'DZD',
  CurrencyCode.egp: 'EGP',
  CurrencyCode.ern: 'ERN',
  CurrencyCode.etb: 'ETB',
  CurrencyCode.eur: 'EUR',
  CurrencyCode.fjd: 'FJD',
  CurrencyCode.fkp: 'FKP',
  CurrencyCode.gbp: 'GBP',
  CurrencyCode.gel: 'GEL',
  CurrencyCode.ghs: 'GHS',
  CurrencyCode.gip: 'GIP',
  CurrencyCode.gmd: 'GMD',
  CurrencyCode.gnf: 'GNF',
  CurrencyCode.gtq: 'GTQ',
  CurrencyCode.gyd: 'GYD',
  CurrencyCode.hkd: 'HKD',
  CurrencyCode.hnl: 'HNL',
  CurrencyCode.hrk: 'HRK',
  CurrencyCode.htg: 'HTG',
  CurrencyCode.huf: 'HUF',
  CurrencyCode.idr: 'IDR',
  CurrencyCode.ils: 'ILS',
  CurrencyCode.inr: 'INR',
  CurrencyCode.iqd: 'IQD',
  CurrencyCode.irr: 'IRR',
  CurrencyCode.isk: 'ISK',
  CurrencyCode.jmd: 'JMD',
  CurrencyCode.jod: 'JOD',
  CurrencyCode.jpy: 'JPY',
  CurrencyCode.kes: 'KES',
  CurrencyCode.kgs: 'KGS',
  CurrencyCode.khr: 'KHR',
  CurrencyCode.kmf: 'KMF',
  CurrencyCode.kpw: 'KPW',
  CurrencyCode.krw: 'KRW',
  CurrencyCode.kwd: 'KWD',
  CurrencyCode.kyd: 'KYD',
  CurrencyCode.kzt: 'KZT',
  CurrencyCode.lak: 'LAK',
  CurrencyCode.lbp: 'LBP',
  CurrencyCode.lkr: 'LKR',
  CurrencyCode.lrd: 'LRD',
  CurrencyCode.lsl: 'LSL',
  CurrencyCode.lyd: 'LYD',
  CurrencyCode.mad: 'MAD',
  CurrencyCode.mdl: 'MDL',
  CurrencyCode.mga: 'MGA',
  CurrencyCode.mkd: 'MKD',
  CurrencyCode.mmk: 'MMK',
  CurrencyCode.mnt: 'MNT',
  CurrencyCode.mop: 'MOP',
  CurrencyCode.mru: 'MRU',
  CurrencyCode.mur: 'MUR',
  CurrencyCode.mvr: 'MVR',
  CurrencyCode.mwk: 'MWK',
  CurrencyCode.mxn: 'MXN',
  CurrencyCode.myr: 'MYR',
  CurrencyCode.mzn: 'MZN',
  CurrencyCode.nad: 'NAD',
  CurrencyCode.ngn: 'NGN',
  CurrencyCode.nio: 'NIO',
  CurrencyCode.nok: 'NOK',
  CurrencyCode.npr: 'NPR',
  CurrencyCode.nzd: 'NZD',
  CurrencyCode.omr: 'OMR',
  CurrencyCode.pab: 'PAB',
  CurrencyCode.pen: 'PEN',
  CurrencyCode.pgk: 'PGK',
  CurrencyCode.php: 'PHP',
  CurrencyCode.pkr: 'PKR',
  CurrencyCode.pln: 'PLN',
  CurrencyCode.pyg: 'PYG',
  CurrencyCode.qar: 'QAR',
  CurrencyCode.ron: 'RON',
  CurrencyCode.rsd: 'RSD',
  CurrencyCode.rub: 'RUB',
  CurrencyCode.rwf: 'RWF',
  CurrencyCode.sar: 'SAR',
  CurrencyCode.sbd: 'SBD',
  CurrencyCode.scr: 'SCR',
  CurrencyCode.sdg: 'SDG',
  CurrencyCode.sek: 'SEK',
  CurrencyCode.sgd: 'SGD',
  CurrencyCode.shp: 'SHP',
  CurrencyCode.sll: 'SLL',
  CurrencyCode.sos: 'SOS',
  CurrencyCode.srd: 'SRD',
  CurrencyCode.ssp: 'SSP',
  CurrencyCode.stn: 'STN',
  CurrencyCode.svc: 'SVC',
  CurrencyCode.syp: 'SYP',
  CurrencyCode.szl: 'SZL',
  CurrencyCode.thb: 'THB',
  CurrencyCode.tjs: 'TJS',
  CurrencyCode.tmt: 'TMT',
  CurrencyCode.tnd: 'TND',
  CurrencyCode.top: 'TOP',
  CurrencyCode.try_: 'TRY',
  CurrencyCode.ttd: 'TTD',
  CurrencyCode.twd: 'TWD',
  CurrencyCode.tzs: 'TZS',
  CurrencyCode.uah: 'UAH',
  CurrencyCode.ugx: 'UGX',
  CurrencyCode.usd: 'USD',
  CurrencyCode.uyu: 'UYU',
  CurrencyCode.uzs: 'UZS',
  CurrencyCode.ves: 'VES',
  CurrencyCode.vnd: 'VND',
  CurrencyCode.vuv: 'VUV',
  CurrencyCode.wst: 'WST',
  CurrencyCode.xaf: 'XAF',
  CurrencyCode.xcd: 'XCD',
  CurrencyCode.xof: 'XOF',
  CurrencyCode.xpf: 'XPF',
  CurrencyCode.yer: 'YER',
  CurrencyCode.zar: 'ZAR',
  CurrencyCode.zmw: 'ZMW',
  CurrencyCode.zwl: 'ZWL',
};

const _$LanguageCodeEnumMap = {
  LanguageCode.af: 'af',
  LanguageCode.ak: 'ak',
  LanguageCode.am: 'am',
  LanguageCode.ar: 'ar',
  LanguageCode.as_: 'as',
  LanguageCode.az: 'az',
  LanguageCode.be: 'be',
  LanguageCode.bg: 'bg',
  LanguageCode.bm: 'bm',
  LanguageCode.bn: 'bn',
  LanguageCode.bo: 'bo',
  LanguageCode.br: 'br',
  LanguageCode.bs: 'bs',
  LanguageCode.ca: 'ca',
  LanguageCode.ce: 'ce',
  LanguageCode.co: 'co',
  LanguageCode.cs: 'cs',
  LanguageCode.cu: 'cu',
  LanguageCode.cy: 'cy',
  LanguageCode.da: 'da',
  LanguageCode.de: 'de',
  LanguageCode.deAt: 'de_AT',
  LanguageCode.deCh: 'de_CH',
  LanguageCode.dz: 'dz',
  LanguageCode.ee: 'ee',
  LanguageCode.el: 'el',
  LanguageCode.en: 'en',
  LanguageCode.enAu: 'en_AU',
  LanguageCode.enCa: 'en_CA',
  LanguageCode.enGb: 'en_GB',
  LanguageCode.enUs: 'en_US',
  LanguageCode.eo: 'eo',
  LanguageCode.es: 'es',
  LanguageCode.esEs: 'es_ES',
  LanguageCode.esMx: 'es_MX',
  LanguageCode.et: 'et',
  LanguageCode.eu: 'eu',
  LanguageCode.fa: 'fa',
  LanguageCode.faAf: 'fa_AF',
  LanguageCode.ff: 'ff',
  LanguageCode.fi: 'fi',
  LanguageCode.fo: 'fo',
  LanguageCode.fr: 'fr',
  LanguageCode.frCa: 'fr_CA',
  LanguageCode.frCh: 'fr_CH',
  LanguageCode.fy: 'fy',
  LanguageCode.ga: 'ga',
  LanguageCode.gd: 'gd',
  LanguageCode.gl: 'gl',
  LanguageCode.gu: 'gu',
  LanguageCode.gv: 'gv',
  LanguageCode.ha: 'ha',
  LanguageCode.he: 'he',
  LanguageCode.hi: 'hi',
  LanguageCode.hr: 'hr',
  LanguageCode.ht: 'ht',
  LanguageCode.hu: 'hu',
  LanguageCode.hy: 'hy',
  LanguageCode.ia: 'ia',
  LanguageCode.id: 'id',
  LanguageCode.ig: 'ig',
  LanguageCode.ii: 'ii',
  LanguageCode.is_: 'is',
  LanguageCode.it: 'it',
  LanguageCode.ja: 'ja',
  LanguageCode.jv: 'jv',
  LanguageCode.ka: 'ka',
  LanguageCode.ki: 'ki',
  LanguageCode.kk: 'kk',
  LanguageCode.kl: 'kl',
  LanguageCode.km: 'km',
  LanguageCode.kn: 'kn',
  LanguageCode.ko: 'ko',
  LanguageCode.ks: 'ks',
  LanguageCode.ku: 'ku',
  LanguageCode.kw: 'kw',
  LanguageCode.ky: 'ky',
  LanguageCode.la: 'la',
  LanguageCode.lb: 'lb',
  LanguageCode.lg: 'lg',
  LanguageCode.ln: 'ln',
  LanguageCode.lo: 'lo',
  LanguageCode.lt: 'lt',
  LanguageCode.lu: 'lu',
  LanguageCode.lv: 'lv',
  LanguageCode.mg: 'mg',
  LanguageCode.mi: 'mi',
  LanguageCode.mk: 'mk',
  LanguageCode.ml: 'ml',
  LanguageCode.mn: 'mn',
  LanguageCode.mr: 'mr',
  LanguageCode.ms: 'ms',
  LanguageCode.mt: 'mt',
  LanguageCode.my: 'my',
  LanguageCode.nb: 'nb',
  LanguageCode.nd: 'nd',
  LanguageCode.ne: 'ne',
  LanguageCode.nl: 'nl',
  LanguageCode.nlBe: 'nl_BE',
  LanguageCode.nn: 'nn',
  LanguageCode.ny: 'ny',
  LanguageCode.om: 'om',
  LanguageCode.or: 'or',
  LanguageCode.os: 'os',
  LanguageCode.pa: 'pa',
  LanguageCode.pl: 'pl',
  LanguageCode.ps: 'ps',
  LanguageCode.pt: 'pt',
  LanguageCode.ptBr: 'pt_BR',
  LanguageCode.ptPt: 'pt_PT',
  LanguageCode.qu: 'qu',
  LanguageCode.rm: 'rm',
  LanguageCode.rn: 'rn',
  LanguageCode.ro: 'ro',
  LanguageCode.roMd: 'ro_MD',
  LanguageCode.ru: 'ru',
  LanguageCode.rw: 'rw',
  LanguageCode.sa: 'sa',
  LanguageCode.sd: 'sd',
  LanguageCode.se: 'se',
  LanguageCode.sg: 'sg',
  LanguageCode.si: 'si',
  LanguageCode.sk: 'sk',
  LanguageCode.sl: 'sl',
  LanguageCode.sm: 'sm',
  LanguageCode.sn: 'sn',
  LanguageCode.so: 'so',
  LanguageCode.sq: 'sq',
  LanguageCode.sr: 'sr',
  LanguageCode.st: 'st',
  LanguageCode.su: 'su',
  LanguageCode.sv: 'sv',
  LanguageCode.sw: 'sw',
  LanguageCode.swCd: 'sw_CD',
  LanguageCode.ta: 'ta',
  LanguageCode.te: 'te',
  LanguageCode.tg: 'tg',
  LanguageCode.th: 'th',
  LanguageCode.ti: 'ti',
  LanguageCode.tk: 'tk',
  LanguageCode.to: 'to',
  LanguageCode.tr: 'tr',
  LanguageCode.tt: 'tt',
  LanguageCode.ug: 'ug',
  LanguageCode.uk: 'uk',
  LanguageCode.ur: 'ur',
  LanguageCode.uz: 'uz',
  LanguageCode.vi: 'vi',
  LanguageCode.vo: 'vo',
  LanguageCode.wo: 'wo',
  LanguageCode.xh: 'xh',
  LanguageCode.yi: 'yi',
  LanguageCode.yo: 'yo',
  LanguageCode.zh: 'zh',
  LanguageCode.zhHans: 'zh_Hans',
  LanguageCode.zhHant: 'zh_Hant',
  LanguageCode.zu: 'zu',
};
