// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_variant.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductVariant _$ProductVariantFromJson(Map json) =>
    $checkedCreate('ProductVariant', json, ($checkedConvert) {
      final val = ProductVariant(
        assets: $checkedConvert(
          'assets',
          (v) => (v as List<dynamic>?)
              ?.map((e) => Asset.fromJson(Map<String, dynamic>.from(e as Map)))
              .toList(),
        ),
        createdAt: $checkedConvert(
          'createdAt',
          (v) => v == null ? null : DateTime.parse(v as String),
        ),
        currencyCode: $checkedConvert(
          'currencyCode',
          (v) => $enumDecodeNullable(_$CurrencyCodeEnumMap, v),
        ),
        customFields: $checkedConvert(
          'customFields',
          (v) => (v as Map?)?.map((k, e) => MapEntry(k as String, e)),
        ),
        facetValues: $checkedConvert(
          'facetValues',
          (v) => (v as List<dynamic>?)
              ?.map(
                (e) => FacetValue.fromJson(Map<String, dynamic>.from(e as Map)),
              )
              .toList(),
        ),
        featuredAsset: $checkedConvert(
          'featuredAsset',
          (v) => v == null
              ? null
              : Asset.fromJson(Map<String, dynamic>.from(v as Map)),
        ),
        id: $checkedConvert('id', (v) => v as String?),
        languageCode: $checkedConvert(
          'languageCode',
          (v) => $enumDecodeNullable(_$LanguageCodeEnumMap, v),
        ),
        name: $checkedConvert('name', (v) => v as String?),
        options: $checkedConvert(
          'options',
          (v) => (v as List<dynamic>?)
              ?.map(
                (e) =>
                    ProductOption.fromJson(Map<String, dynamic>.from(e as Map)),
              )
              .toList(),
        ),
        price: $checkedConvert('price', (v) => (v as num?)?.toDouble()),
        priceWithTax: $checkedConvert(
          'priceWithTax',
          (v) => (v as num?)?.toDouble(),
        ),
        productId: $checkedConvert('productId', (v) => v as String?),
        sku: $checkedConvert('sku', (v) => v as String?),
        stockLevel: $checkedConvert('stockLevel', (v) => v as String?),
        taxCategory: $checkedConvert(
          'taxCategory',
          (v) => v == null
              ? null
              : TaxCategory.fromJson(Map<String, dynamic>.from(v as Map)),
        ),
        translations: $checkedConvert(
          'translations',
          (v) => (v as List<dynamic>?)
              ?.map(
                (e) => ProductVariantTranslation.fromJson(
                  Map<String, dynamic>.from(e as Map),
                ),
              )
              .toList(),
        ),
        updatedAt: $checkedConvert(
          'updatedAt',
          (v) => v == null ? null : DateTime.parse(v as String),
        ),
      );
      return val;
    });

Map<String, dynamic> _$ProductVariantToJson(ProductVariant instance) =>
    <String, dynamic>{
      'assets': ?instance.assets?.map((e) => e.toJson()).toList(),
      'createdAt': ?instance.createdAt?.toIso8601String(),
      'currencyCode': ?_$CurrencyCodeEnumMap[instance.currencyCode],
      'customFields': ?instance.customFields,
      'facetValues': ?instance.facetValues?.map((e) => e.toJson()).toList(),
      'featuredAsset': ?instance.featuredAsset?.toJson(),
      'id': ?instance.id,
      'languageCode': ?_$LanguageCodeEnumMap[instance.languageCode],
      'name': ?instance.name,
      'options': ?instance.options?.map((e) => e.toJson()).toList(),
      'price': ?instance.price,
      'priceWithTax': ?instance.priceWithTax,
      'productId': ?instance.productId,
      'sku': ?instance.sku,
      'stockLevel': ?instance.stockLevel,
      'taxCategory': ?instance.taxCategory?.toJson(),
      'translations': ?instance.translations?.map((e) => e.toJson()).toList(),
      'updatedAt': ?instance.updatedAt?.toIso8601String(),
    };

const _$CurrencyCodeEnumMap = {
  CurrencyCode.AED: 'AED',
  CurrencyCode.AFN: 'AFN',
  CurrencyCode.ALL: 'ALL',
  CurrencyCode.AMD: 'AMD',
  CurrencyCode.ANG: 'ANG',
  CurrencyCode.AOA: 'AOA',
  CurrencyCode.ARS: 'ARS',
  CurrencyCode.AUD: 'AUD',
  CurrencyCode.AWG: 'AWG',
  CurrencyCode.AZN: 'AZN',
  CurrencyCode.BAM: 'BAM',
  CurrencyCode.BBD: 'BBD',
  CurrencyCode.BDT: 'BDT',
  CurrencyCode.BGN: 'BGN',
  CurrencyCode.BHD: 'BHD',
  CurrencyCode.BIF: 'BIF',
  CurrencyCode.BMD: 'BMD',
  CurrencyCode.BND: 'BND',
  CurrencyCode.BOB: 'BOB',
  CurrencyCode.BRL: 'BRL',
  CurrencyCode.BSD: 'BSD',
  CurrencyCode.BTN: 'BTN',
  CurrencyCode.BWP: 'BWP',
  CurrencyCode.BYN: 'BYN',
  CurrencyCode.BZD: 'BZD',
  CurrencyCode.CAD: 'CAD',
  CurrencyCode.CDF: 'CDF',
  CurrencyCode.CHF: 'CHF',
  CurrencyCode.CLP: 'CLP',
  CurrencyCode.CNY: 'CNY',
  CurrencyCode.COP: 'COP',
  CurrencyCode.CRC: 'CRC',
  CurrencyCode.CUC: 'CUC',
  CurrencyCode.CUP: 'CUP',
  CurrencyCode.CVE: 'CVE',
  CurrencyCode.CZK: 'CZK',
  CurrencyCode.DJF: 'DJF',
  CurrencyCode.DKK: 'DKK',
  CurrencyCode.DOP: 'DOP',
  CurrencyCode.DZD: 'DZD',
  CurrencyCode.EGP: 'EGP',
  CurrencyCode.ERN: 'ERN',
  CurrencyCode.ETB: 'ETB',
  CurrencyCode.EUR: 'EUR',
  CurrencyCode.FJD: 'FJD',
  CurrencyCode.FKP: 'FKP',
  CurrencyCode.GBP: 'GBP',
  CurrencyCode.GEL: 'GEL',
  CurrencyCode.GHS: 'GHS',
  CurrencyCode.GIP: 'GIP',
  CurrencyCode.GMD: 'GMD',
  CurrencyCode.GNF: 'GNF',
  CurrencyCode.GTQ: 'GTQ',
  CurrencyCode.GYD: 'GYD',
  CurrencyCode.HKD: 'HKD',
  CurrencyCode.HNL: 'HNL',
  CurrencyCode.HRK: 'HRK',
  CurrencyCode.HTG: 'HTG',
  CurrencyCode.HUF: 'HUF',
  CurrencyCode.IDR: 'IDR',
  CurrencyCode.ILS: 'ILS',
  CurrencyCode.INR: 'INR',
  CurrencyCode.IQD: 'IQD',
  CurrencyCode.IRR: 'IRR',
  CurrencyCode.ISK: 'ISK',
  CurrencyCode.JMD: 'JMD',
  CurrencyCode.JOD: 'JOD',
  CurrencyCode.JPY: 'JPY',
  CurrencyCode.KES: 'KES',
  CurrencyCode.KGS: 'KGS',
  CurrencyCode.KHR: 'KHR',
  CurrencyCode.KMF: 'KMF',
  CurrencyCode.KPW: 'KPW',
  CurrencyCode.KRW: 'KRW',
  CurrencyCode.KWD: 'KWD',
  CurrencyCode.KYD: 'KYD',
  CurrencyCode.KZT: 'KZT',
  CurrencyCode.LAK: 'LAK',
  CurrencyCode.LBP: 'LBP',
  CurrencyCode.LKR: 'LKR',
  CurrencyCode.LRD: 'LRD',
  CurrencyCode.LSL: 'LSL',
  CurrencyCode.LYD: 'LYD',
  CurrencyCode.MAD: 'MAD',
  CurrencyCode.MDL: 'MDL',
  CurrencyCode.MGA: 'MGA',
  CurrencyCode.MKD: 'MKD',
  CurrencyCode.MMK: 'MMK',
  CurrencyCode.MNT: 'MNT',
  CurrencyCode.MOP: 'MOP',
  CurrencyCode.MRU: 'MRU',
  CurrencyCode.MUR: 'MUR',
  CurrencyCode.MVR: 'MVR',
  CurrencyCode.MWK: 'MWK',
  CurrencyCode.MXN: 'MXN',
  CurrencyCode.MYR: 'MYR',
  CurrencyCode.MZN: 'MZN',
  CurrencyCode.NAD: 'NAD',
  CurrencyCode.NGN: 'NGN',
  CurrencyCode.NIO: 'NIO',
  CurrencyCode.NOK: 'NOK',
  CurrencyCode.NPR: 'NPR',
  CurrencyCode.NZD: 'NZD',
  CurrencyCode.OMR: 'OMR',
  CurrencyCode.PAB: 'PAB',
  CurrencyCode.PEN: 'PEN',
  CurrencyCode.PGK: 'PGK',
  CurrencyCode.PHP: 'PHP',
  CurrencyCode.PKR: 'PKR',
  CurrencyCode.PLN: 'PLN',
  CurrencyCode.PYG: 'PYG',
  CurrencyCode.QAR: 'QAR',
  CurrencyCode.RON: 'RON',
  CurrencyCode.RSD: 'RSD',
  CurrencyCode.RUB: 'RUB',
  CurrencyCode.RWF: 'RWF',
  CurrencyCode.SAR: 'SAR',
  CurrencyCode.SBD: 'SBD',
  CurrencyCode.SCR: 'SCR',
  CurrencyCode.SDG: 'SDG',
  CurrencyCode.SEK: 'SEK',
  CurrencyCode.SGD: 'SGD',
  CurrencyCode.SHP: 'SHP',
  CurrencyCode.SLL: 'SLL',
  CurrencyCode.SOS: 'SOS',
  CurrencyCode.SRD: 'SRD',
  CurrencyCode.SSP: 'SSP',
  CurrencyCode.STN: 'STN',
  CurrencyCode.SVC: 'SVC',
  CurrencyCode.SYP: 'SYP',
  CurrencyCode.SZL: 'SZL',
  CurrencyCode.THB: 'THB',
  CurrencyCode.TJS: 'TJS',
  CurrencyCode.TMT: 'TMT',
  CurrencyCode.TND: 'TND',
  CurrencyCode.TOP: 'TOP',
  CurrencyCode.TRY: 'TRY',
  CurrencyCode.TTD: 'TTD',
  CurrencyCode.TWD: 'TWD',
  CurrencyCode.TZS: 'TZS',
  CurrencyCode.UAH: 'UAH',
  CurrencyCode.UGX: 'UGX',
  CurrencyCode.USD: 'USD',
  CurrencyCode.UYU: 'UYU',
  CurrencyCode.UZS: 'UZS',
  CurrencyCode.VES: 'VES',
  CurrencyCode.VND: 'VND',
  CurrencyCode.VUV: 'VUV',
  CurrencyCode.WST: 'WST',
  CurrencyCode.XAF: 'XAF',
  CurrencyCode.XCD: 'XCD',
  CurrencyCode.XOF: 'XOF',
  CurrencyCode.XPF: 'XPF',
  CurrencyCode.YER: 'YER',
  CurrencyCode.ZAR: 'ZAR',
  CurrencyCode.ZMW: 'ZMW',
  CurrencyCode.ZWL: 'ZWL',
};

const _$LanguageCodeEnumMap = {
  LanguageCode.af: 'af',
  LanguageCode.ak: 'ak',
  LanguageCode.sq: 'sq',
  LanguageCode.am: 'am',
  LanguageCode.ar: 'ar',
  LanguageCode.hy: 'hy',
  LanguageCode.as_: 'as',
  LanguageCode.az: 'az',
  LanguageCode.bm: 'bm',
  LanguageCode.bn: 'bn',
  LanguageCode.eu: 'eu',
  LanguageCode.be: 'be',
  LanguageCode.bs: 'bs',
  LanguageCode.br: 'br',
  LanguageCode.bg: 'bg',
  LanguageCode.my: 'my',
  LanguageCode.ca: 'ca',
  LanguageCode.ce: 'ce',
  LanguageCode.zh: 'zh',
  LanguageCode.zh_Hans: 'zh_Hans',
  LanguageCode.zh_Hant: 'zh_Hant',
  LanguageCode.cu: 'cu',
  LanguageCode.kw: 'kw',
  LanguageCode.co: 'co',
  LanguageCode.hr: 'hr',
  LanguageCode.cs: 'cs',
  LanguageCode.da: 'da',
  LanguageCode.nl: 'nl',
  LanguageCode.nl_BE: 'nl_BE',
  LanguageCode.dz: 'dz',
  LanguageCode.en: 'en',
  LanguageCode.en_AU: 'en_AU',
  LanguageCode.en_CA: 'en_CA',
  LanguageCode.en_GB: 'en_GB',
  LanguageCode.en_US: 'en_US',
  LanguageCode.eo: 'eo',
  LanguageCode.et: 'et',
  LanguageCode.ee: 'ee',
  LanguageCode.fo: 'fo',
  LanguageCode.fi: 'fi',
  LanguageCode.fr: 'fr',
  LanguageCode.fr_CA: 'fr_CA',
  LanguageCode.fr_CH: 'fr_CH',
  LanguageCode.ff: 'ff',
  LanguageCode.gl: 'gl',
  LanguageCode.lg: 'lg',
  LanguageCode.ka: 'ka',
  LanguageCode.de: 'de',
  LanguageCode.de_AT: 'de_AT',
  LanguageCode.de_CH: 'de_CH',
  LanguageCode.el: 'el',
  LanguageCode.gu: 'gu',
  LanguageCode.ht: 'ht',
  LanguageCode.ha: 'ha',
  LanguageCode.he: 'he',
  LanguageCode.hi: 'hi',
  LanguageCode.hu: 'hu',
  LanguageCode.is_: 'is',
  LanguageCode.ig: 'ig',
  LanguageCode.id: 'id',
  LanguageCode.ia: 'ia',
  LanguageCode.ga: 'ga',
  LanguageCode.it: 'it',
  LanguageCode.ja: 'ja',
  LanguageCode.jv: 'jv',
  LanguageCode.kl: 'kl',
  LanguageCode.kn: 'kn',
  LanguageCode.ks: 'ks',
  LanguageCode.kk: 'kk',
  LanguageCode.km: 'km',
  LanguageCode.ki: 'ki',
  LanguageCode.rw: 'rw',
  LanguageCode.ko: 'ko',
  LanguageCode.ku: 'ku',
  LanguageCode.ky: 'ky',
  LanguageCode.lo: 'lo',
  LanguageCode.la: 'la',
  LanguageCode.lv: 'lv',
  LanguageCode.ln: 'ln',
  LanguageCode.lt: 'lt',
  LanguageCode.lu: 'lu',
  LanguageCode.lb: 'lb',
  LanguageCode.mk: 'mk',
  LanguageCode.mg: 'mg',
  LanguageCode.ms: 'ms',
  LanguageCode.ml: 'ml',
  LanguageCode.mt: 'mt',
  LanguageCode.gv: 'gv',
  LanguageCode.mi: 'mi',
  LanguageCode.mr: 'mr',
  LanguageCode.mn: 'mn',
  LanguageCode.ne: 'ne',
  LanguageCode.nd: 'nd',
  LanguageCode.se: 'se',
  LanguageCode.nb: 'nb',
  LanguageCode.nn: 'nn',
  LanguageCode.ny: 'ny',
  LanguageCode.or: 'or',
  LanguageCode.om: 'om',
  LanguageCode.os: 'os',
  LanguageCode.ps: 'ps',
  LanguageCode.fa: 'fa',
  LanguageCode.fa_AF: 'fa_AF',
  LanguageCode.pl: 'pl',
  LanguageCode.pt: 'pt',
  LanguageCode.pt_BR: 'pt_BR',
  LanguageCode.pt_PT: 'pt_PT',
  LanguageCode.pa: 'pa',
  LanguageCode.qu: 'qu',
  LanguageCode.ro: 'ro',
  LanguageCode.ro_MD: 'ro_MD',
  LanguageCode.rm: 'rm',
  LanguageCode.rn: 'rn',
  LanguageCode.ru: 'ru',
  LanguageCode.sm: 'sm',
  LanguageCode.sg: 'sg',
  LanguageCode.sa: 'sa',
  LanguageCode.gd: 'gd',
  LanguageCode.sr: 'sr',
  LanguageCode.sn: 'sn',
  LanguageCode.ii: 'ii',
  LanguageCode.sd: 'sd',
  LanguageCode.si: 'si',
  LanguageCode.sk: 'sk',
  LanguageCode.sl: 'sl',
  LanguageCode.so: 'so',
  LanguageCode.st: 'st',
  LanguageCode.es: 'es',
  LanguageCode.es_ES: 'es_ES',
  LanguageCode.es_MX: 'es_MX',
  LanguageCode.su: 'su',
  LanguageCode.sw: 'sw',
  LanguageCode.sw_CD: 'sw_CD',
  LanguageCode.sv: 'sv',
  LanguageCode.tg: 'tg',
  LanguageCode.ta: 'ta',
  LanguageCode.tt: 'tt',
  LanguageCode.te: 'te',
  LanguageCode.th: 'th',
  LanguageCode.bo: 'bo',
  LanguageCode.ti: 'ti',
  LanguageCode.to: 'to',
  LanguageCode.tr: 'tr',
  LanguageCode.tk: 'tk',
  LanguageCode.uk: 'uk',
  LanguageCode.ur: 'ur',
  LanguageCode.ug: 'ug',
  LanguageCode.uz: 'uz',
  LanguageCode.vi: 'vi',
  LanguageCode.vo: 'vo',
  LanguageCode.cy: 'cy',
  LanguageCode.fy: 'fy',
  LanguageCode.wo: 'wo',
  LanguageCode.xh: 'xh',
  LanguageCode.yi: 'yi',
  LanguageCode.yo: 'yo',
  LanguageCode.zu: 'zu',
};
