// Auto-generated by Zorphy
// Generated at: 2026-08-13T22:58:32.752544

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../date_operators/date_operators.dart';
import '../id_operators/id_operators.dart';
import '../string_operators/string_operators.dart';
import '../customer_filter_parameter/customer_filter_parameter.dart';

part 'customer_filter_parameter.zorphy.dart';
part 'customer_filter_parameter.g.dart';

/// CustomerFilterParameter entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $CustomerFilterParameter {

  @JsonKey(name: '_and')
  List<$CustomerFilterParameter>? get and;
  @JsonKey(name: '_or')
  List<$CustomerFilterParameter>? get or;
  $DateOperators? get createdAt;
  $StringOperators? get emailAddress;
  $StringOperators? get firstName;
  $IdOperators? get id;
  $StringOperators? get lastName;
  $StringOperators? get phoneNumber;
  $StringOperators? get title;
  $DateOperators? get updatedAt;
}

